### ISSUE TITLE
False Positive: Yara Rules for FiveEyes being flagged as an alert

### ISSUE THREAD

**Issue by staticrez** [Neo23x0/Loki#1]
see attached
![loki_fp](https://cloud.githubusercontent.com/assets/10157111/5878761/49b1e954-a2f7-11e4-9980-a21f898f6845.png)

**Comment by Neo23x0** [comment]
Thanks - this is fixed in the next version. The upcoming 0.3 will include a lot of rules that we borrowed from our commercial scanner. Will be release next week (Mon/Tue). 
If you need a quick solution, just add the MD5 of the rule file to the 'falsepositive-hashes.txt'.

**Comment by Neo23x0** [comment]
Closed with version 0.3
