### ISSUE TITLE
False positives scanning self folder

### ISSUE THREAD

**Issue by inire** [Neo23x0/Loki#10]
When I ran the scan this morning the scan found a ton of issues in the downloads folder where the Loki scanner was.

command line was simply loki.exe

http://pastebin.com/FJ2W8Wfb

thanks! great tool.

**Comment by Neo23x0** [comment]
How did you run loki.exe? (did you add the directory to the PATH variable? 
Did you execute the loki.exe in C:\Users\USERNAME\Downloads\Loki-master\Loki-master\ or a copy of it somewhere else on disk?
The program automatically excludes the working directory from the scan.

**Comment by inire** [comment]
started command line in administrator mode.
executed file loki.exe in the C:\Users\USERNAME\Downloads\Loki-master\Loki-master\ folder.
no options, just the exe by itself.

**Comment by Neo23x0** [comment]
Could you check if this still happens with version 0.7.1of the loki.exe which I uploaded a few minutes ago?

**Comment by inire** [comment]
downloading, testing. will reply back. thanks.

**Comment by Neo23x0** [comment]
You could speed things up by using
loki.exe --noprocs -p C:\Users\USERNAME\Downloads

**Comment by Neo23x0** [comment]
Ah - it's a problem with the long path because sys.executable gives the DOS 8 character directories names in its response:
C:\Users\neo\DOWNLO~1\LOKI-M~1\loki.exe
1 C:\Users\neo\DOWNLO~1\LOKI-M~1
Test: C:\Users\neo\DOWNLO~1\LOKI-M~1

I have to find out how the sys module returns an NT path.

**Comment by Neo23x0** [comment]
I think I fixed it now with version 0.7.2 

See the PyInstalled issue: https://github.com/pyinstaller/pyinstaller/issues/1282

**Comment by inire** [comment]
ok, downloaded, and will retest now.

didn't reply to yesterdays (0.7.1) because it didn't finish running for a while.

**Comment by inire** [comment]
Neo,

That did the trick, thanks. No self folder scanning.

Thanks for looking into this and fixing so quickly.
