### ISSUE TITLE
WannaCry match on Size: 0 files

### ISSUE THREAD

**Issue by srcr** [Neo23x0/Loki#100]
I get the following false positives.

> LOKI: Alert: FILE: C:\Program Files (x86)\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin\Microsoft.WindowsAzure.StorageClient.dll SCORE: 100 TYPE: UNKNOWN SIZE: 0 FIRST_BYTES:  /  MD5: d41d8cd98f00b204e9800998ecf8427e SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709 SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 REASON_1: Malware Hash TYPE: MD5 HASH: d41d8cd98f00b204e9800998ecf8427e SUBSCORE: 100 DESC: WannaCry/Wcry Ransomware https://www.virustotal.com/en/file/f01644082db3fa50ba9f4773f11f062ab785c9db02a3a

**Comment by Neo23x0** [comment]
Fixed, thanks
https://github.com/Neo23x0/signature-base/commit/c95a25cc7293c5e8500e5a596306e6d4bd5896ff
