### ISSUE TITLE
WindowsError: "not a valid Win32 application" issue in WinXP 32-bits

### ISSUE THREAD

**Issue by Tux-Panik** [Neo23x0/Loki#102]
Dear,

Thanks for this amazing tool.
Just an issue encountered on a scan of very different machines, especially on a Windows XP (32 bits) using the latest released ; "version 0.26.2".

I have the feeling it is Python related, and Google brings some results about it, but I can't identify where the problem is located:

`[NOTICE] Starting Loki Scan SYSTEM: RICL11 TIME: 20180309T18:02:09Z PLATFORM: windows`
`[NOTICE] PE-Sieve successfully initialized BINARY: C:\Documents and Settings\User\Desktop\Virusdef\Event Logs\LOKI\LOKI_Wannacry\tools/pe-sieve32.exe SOURCE: https://github.com/hasherezade/pe-sieve`
`[INFO] File Name Characteristics initialized with 3 regex patterns`
`[INFO] C2 server indicators initialized with 45 elements`
`[INFO] Malicious MD5 Hashes initialized with 444 hashes`
`[INFO] Malicious SHA1 Hashes initialized with 440 hashes`
`[INFO] Malicious SHA256 Hashes initialized with 466 hashes`
`[INFO] False Positive Hashes initialized with 0 hashes`
`[INFO] Processing YARA rules folder C:\Documents and Settings\User\Desktop\Virusdef\Event Logs\LOKI\LOKI_Wannacry\./signature-base/yara`
`[INFO] Initializing Yara rule crime_wannacry.yar`
`[INFO] Initializing Yara rule wannacry_US-CERT.yar`
`[INFO] Initializing all YARA rules at once (composed string of all rule files)`
`[INFO] Initialized all Yara rules at once`
`[INFO] Reading private rules from binary ...`
`[INFO] Current user has admin rights - very good`
`[INFO] Setting LOKI process with PID: 4692 to priority IDLE`
`[INFO] Skipping Process PID: 0 NAME: System Idle Process OWNER: unknown CMD: N/A PATH: none`
`[INFO] Skipping Process PID: 4 NAME: System OWNER: SYSTEM CMD: N/A PATH: none`
`[INFO] Scanning Process PID: 740 NAME: smss.exe OWNER: SYSTEM CMD: \SystemRoot\System32\smss.exe PATH: C:\WINDOWS\System32\smss.exe`
`Traceback (most recent call last):`
`  File "<string>", line 1474, in <module>`
`  File "<string>", line 680, in scan_processes`
`  File "X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\lib.pesieve", line 60, in scan`
`  File "X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\lib.helpers", line 298, in runProcess`
`  File "X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\subprocess", line 710, in __init__`
`  File "X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\subprocess", line 958, in _execute_child`
`WindowsError: [Error 193] %1 is not a valid Win32 application`

If you have any idea or you encountered the problem, I will be glad to have some tips.
Thanks in advance,
Kind regards,
Julien

**Comment by Neo23x0** [comment]
Remove PESieve from the tools folder. It seems that it doesn't work on XP machines.

**Comment by Tux-Panik** [comment]
You were right Florian. It fixed the issue.
Thanks again for the tool and the support. 
Regards, 
Julien

**Comment by hillu** [comment]
Newer versions of Visual Studio produce binaries incompatible with Windows XP. If you can get PE Sieve built from source using MinGW, this problem will likely go away.
