### ISSUE TITLE
I'm unable to install the tool can you please guide me ?

### ISSUE THREAD

**Issue by vipinshady** [Neo23x0/Loki#104]
As there is no loki.exe file in the repository so i don't understand how to install it.

Can you please help me out with the specific steps to install Loki on my machine ?

**Comment by Neo23x0** [comment]
Check the section in the README for a step-by-step guide
https://github.com/Neo23x0/Loki#how-to-run-loki-and-analyse-the-reports

Or just download the newest version from the release section
https://github.com/Neo23x0/Loki/releases

The ZIP named loki_0.27.1.zip is the newest version.
