### ISSUE TITLE
Error during YARA rule compilation

### ISSUE THREAD

**Issue by arnydo** [Neo23x0/Loki#105]
Running the pre-compiled exe on multiple machines and receiving the following error:

```
RROR] Error during YARA rule compilation - please fix the issue in the rule set
cmd.exe : Traceback (most recent call last):
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  File "<string>", line 1092, in initialize_yara_rules
SyntaxError: line 59214: not enough memory
```

Ran updates and tried multiple machines. The machines do indeed have enough memory.

Any tips?

Thank you.

**Comment by arnydo** [comment]
Determined this only occurs when invoked remotely via Powershell.
A local command prompt shell allows Loki to run successfully.
Possibly a limitation on WinRM memory consumption?

**Comment by Neo23x0** [comment]
Possible. I haven't heard of something like that yet. 

We plan to release a new scanner based on Golang (multi-platform) this autumn. It should avoid problems that arise when PyInstaller "compiled" binaries are used.

**Comment by tonybounty** [comment]
> We plan to release a new scanner based on Golang (multi-platform) this autumn. It should avoid problems that arise when PyInstaller "compiled" binaries are used.

What is the status of the Golang version ?

**Comment by Neo23x0** [comment]
See README 
https://github.com/Neo23x0/Loki#alternatives

Website 
https://www.nextron-systems.com/spark-core/
