### ISSUE TITLE
Error Integrating OTX threat IoCs to Loki

### ISSUE THREAD

**Issue by aiman-aew** [Neo23x0/Loki#106]
I am trying to integrate the OTX Threat API to my Loki tool. Using python 3.7 I did install the OTX python  SDK and add the signature-base file.

However, upon using get-otx-iocs.py I am getting this error
![image](https://user-images.githubusercontent.com/25643954/40300254-69e16292-5cf1-11e8-98d5-4020fcd93ef3.png)

Is there anything specific that I am doing wrong or a missing library that I should add?

**Comment by DrSergey2** [comment]
You need to install “requests” library.

pip3 install requests

**Comment by aiman-aew** [comment]
Hello @DrSergey2 ,

and thank you this solved the problem.

However, I am facing another one as found below
![image](https://user-images.githubusercontent.com/25643954/40302920-7277378a-5cf9-11e8-88b7-c3b3518beec3.png)

Any Idea on why are they being sent as String meanwhile the agent is expecting objects? should I change anything in the API settings
