### ISSUE TITLE
Custom false positives

### ISSUE THREAD

**Issue by erichsteiger** [Neo23x0/Loki#108]
Is there a way to create a custom false positive hash file that would not be overwritten during a signature update? Custom false positives might be environment-specific and not necessarily appropriate for global distribution.

**Comment by Neo23x0** [comment]
You can use the filename IOCs with negative scores for that

E.g. 
\\bin\\nmap\.exe;-150

OR 
hash IOC files that contain the keyword `falspositive` in the filename
https://github.com/Neo23x0/Loki/blob/master/loki.py#L168

**Comment by erichsteiger** [comment]
Got it, thanks!
