### ISSUE TITLE
UnicodeDecodeError when scanning path with special characters

### ISSUE THREAD

**Issue by devyzr** [Neo23x0/Loki#109]
I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1515, in <module>
  File "<string>", line 189, in scan_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 44: ordinal not in range(128)
```

When using the command
```
loki.exe -p "C:\Users\username\Documents\Revisión\"
```
I'm sure it's because of the ó in the scan path, apparently this can be fixed by using UTF-8 encoding, but I haven't read the code, so I'm not sure this is a valid solution.

I tested paths with the following letters in the scan path with the same result:

- á
- é
- í
- ó
- ú
- ä

**Comment by Neo23x0** [comment]
FYI
The alternative scanner SPARK Core, which shouldn't have this issue, has been released this month
https://www.nextron-systems.com/spark-core/

**Comment by devyzr** [comment]
Thanks, I'll give it a try, but I also want to give fixing this a whirl.

I noticed that os.uname instead of platform.uname is used (makes the uncompiled python script uncompatible with windows even though there's an OS check before it's called), as well as python trying to read "/etc/mtab" even when on a windows platform.

I'll try and fix the unicode bug on a Linux platform for now, but should I open another issue for these two problems? Or is there something I'm missing?

**Comment by Neo23x0** [comment]
Shouldn't be a problem anymore with the py3 version
