### ISSUE TITLE
FP detection: adblocker for browser

### ISSUE THREAD

**Issue by gunnersson** [Neo23x0/Loki#11]
[WARNING] Yara Rule MATCH: HackTool_Producers DESCRIPTION: Hacktool Producers String
FILE: C:\Users\gunnersson\AppData\Roaming\Mozilla\Firefox\Profiles\ms9m2yly.defa
ult\extension-data\ublock0.sqlite
MD5: 0ebe6a02d9915317316643b0b458bd0a
SHA1: 4b47e975a254cfa453cf83346b87979598139f0a
SHA256: 8934e7701147166948488cffd6842cb516cdb3f11baea272f2566898e40177af

belongs to
https://github.com/gorhill/uBlock

which is similar to (forked from)
https://github.com/chrisaljoudi/uBlock

**Comment by gunnersson** [comment]
sorry, missing line...

[WARNING] Yara Rule MATCH: HackTool_Producers DESCRIPTION: Hacktool Producers String
FILE: C:\Users\gunnersson\AppData\Roaming\Mozilla\Firefox\Profiles\ms9m2yly.default\extension-data\ublock0.sqlite
MD5: 0ebe6a02d9915317316643b0b458bd0a
SHA1: 4b47e975a254cfa453cf83346b87979598139f0a
SHA256: 8934e7701147166948488cffd6842cb516cdb3f11baea272f2566898e40177af
MATCHES: Str1: ntsecurity.nu

**Comment by gunnersson** [comment]
more info on that extension

https://en.wikipedia.org/wiki/UBlock

**Comment by Neo23x0** [comment]
Adjusted rule and loki
