### ISSUE TITLE
WindowsError: [Error 6] The handle is invalid

### ISSUE THREAD

**Issue by davidep** [Neo23x0/Loki#113]
I'm getting the following error using the current version of Loki, each time after processing smss.exe :
```
Traceback (most recent call last):
  File &quot;&lt;string&gt;&quot;, line 1499, in &lt;module&gt;
  File &quot;&lt;string&gt;&quot;, line 696, in scan_processes
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\lib.pesieve&quot;, line 59, in scan
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\lib.helpers&quot;, line 298, in runProcess
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\subprocess&quot;, line 702, in __init__
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\subprocess&quot;, line 823, in _get_handles
WindowsError: [Error 6] The handle is invalid
```

**Comment by joeshmoe189** [comment]
I also have this same issue! Please let me know if there are any updates on a fix! Thank you

**Comment by Neo23x0** [comment]
Does the scan terminate?

**Comment by joeshmoe189** [comment]
Yes, it gives the same "WindowsError: [Error 6] The handle is invalid" and then just ends.

**Comment by Neo23x0** [comment]
Could you provide the full traceback like davidep did a year ago?

**Comment by joeshmoe189** [comment]
[XXXXXXXXXXXXX] C:\Windows\XXXXXXX\Loki\ >  execfg loki.exe -p C:\ 
                                                                               
      __   ____  __ ______                            
     / /  / __ \/ //_/  _/                            
    / /__/ /_/ / ,&lt; _/ /                              
   /____/\____/_/|_/___/                              
      ________  _____  ____                           
     /  _/ __ \/ ___/ / __/______ ____  ___  ___ ____ 
    _/ // /_/ / /__  _\ \/ __/ _ `/ _ \/ _ \/ -_) __/ 
   /___/\____/\___/ /___/\__/\_,_/_//_/_//_/\__/_/    

   Copyright by Florian Roth, Released under the GNU General Public License
   Version 0.30.3
  
   DISCLAIMER - USE AT YOUR OWN RISK
   Please report false positives via https://github.com/Neo23x0/Loki/issues
  
                                                                               

  [NOTICE] Starting Loki Scan VERSION: 0.30.3 SYSTEM: XXXXXXXX TIME: 20191016T13:50:57Z PLATFORM: 10 10.0.16299  Multiprocessor Free PROC: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel ARCH: 32bit WindowsPE
  [NOTICE] Registered plugin PluginWMI
  [NOTICE] Loaded plugin C:\Windows\XXXXXX\Loki\plugins\loki-plugin-wmi.py
  [NOTICE] PE-Sieve successfully initialized BINARY: C:\Windows\XXXXXXXX\Loki\Loki\Loki\tools\pe-sieve64.exe SOURCE: https://github.com/hasherezade/pe-sieve
  [INFO] File Name Characteristics initialized with 2753 regex patterns
  [INFO] C2 server indicators initialized with 33578 elements
  [INFO] Malicious MD5 Hashes initialized with 18976 hashes
  [INFO] Malicious SHA1 Hashes initialized with 7046 hashes
  [INFO] Malicious SHA256 Hashes initialized with 22675 hashes
  [INFO] False Positive Hashes initialized with 30 hashes
  [INFO] Processing YARA rules folder C:\Windows\XXXXXXXX\Loki\Loki\Loki\signature-base\yara
  [INFO] Initializing all YARA rules at once (composed string of all rule files)
  [INFO] Initialized 439 Yara rules
  [INFO] Reading private rules from binary ...
  [INFO] Current user has admin rights - very good
  [INFO] Setting LOKI process with PID: 4984 to priority IDLE
  [NOTICE] Running plugin PluginWMI
  [NOTICE] Finished running plugin PluginWMI
  [INFO] Skipping Process PID: 0 NAME: System Idle Process OWNER: unknown CMD: N/A PATH: none
  [INFO] Skipping Process PID: 4 NAME: System OWNER: SYSTEM CMD: N/A PATH: none
  [INFO] Scanning Process PID: 520 NAME: smss.exe OWNER: SYSTEM CMD: N/A PATH: none
Traceback (most recent call last):
  File &quot;&lt;string&gt;&quot;, line 1559, in &lt;module&gt;
  File &quot;&lt;string&gt;&quot;, line 702, in scan_processes
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\lib.pesieve&quot;, line 59, in scan
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\lib.helpers&quot;, line 298, in runProcess
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\subprocess&quot;, line 386, in __init__
  File &quot;X:\Workspace\Loki\build\loki-noprivrules-win2003sup\out00-PYZ.pyz\subprocess&quot;, line 509, in _get_handles
WindowsError: [Error 6] The handle is invalid

**Comment by joeshmoe189** [comment]
Hello again @Neo23x0 , So the fix worked and it was able to run but now I am getting errors like this over and over again.

20191017T14:45:39Z BAH5CG8253SL9 LOKI: Error: MODULE: FileScan MESSAGE: [Error 3] The system cannot find the path specified: u'C:\\Documents and Settings\\*****\\AppData\\Local\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Application Data\\Temporary Internet Files\\Low\\IE\\S6TPIECF\\*.*'

**Comment by Neo23x0** [comment]
That's a symbolic link problem on your partition and not LOKI related. 

e.g. see
https://www.sevenforums.com/general-discussion/115149-stop-application-data-folder-replicating.html 

and 
https://www.bleepingcomputer.com/forums/t/674054/dozens-of-application-data-folders-nestedembedded/
