### ISSUE TITLE
Duplicate identifier after update EXP_DriveCrypt_x64passldr

### ISSUE THREAD

**Issue by crapwarelabs** [Neo23x0/Loki#116]
Traceback (most recent call last):
 File "/nsm/Loki/loki.py", line 1083, in initialize_yara_rules
   'md5': dummy
SyntaxError: line 33277: duplicated identifier "EXP_DriveCrypt_x64passldr"

**Comment by Neo23x0** [comment]
ah, I renamed that rule and the upgrader doesn't remove the old rule names

Just remove the old rule file `exp_drivecrypt.yar` in your `./signature-base/yara` directory.
