### ISSUE TITLE
unclear detection, probably FP

### ISSUE THREAD

**Issue by gunnersson** [Neo23x0/Loki#12]
[WARNING] Yara Rule MATCH: Base64_encoded_Executable DESCRIPTION: Detects an base64 encoded executable (often embedded)
FILE: C:\Users\gunnersson\AppData\Roaming\Thunderbird\Profiles\p34nq9d8.default\ImapMail\posteo.de\INBOX.sbd\Archiv.sbd\Security
MD5: 6787d69b56b4ada44544c395ccbc65f5
SHA1: 36fb81c40d849441a0749ee262385ef2d18bd356
SHA256: 3bdb01148ecd76e7ddf62ad618788aac385a8c3761ebca237a9ae2f80d937ead
MATCHES: Str1: TVqQAAMAAAAEAAAA//8AALgAAAA

in that saved e-mails Thunderbird folder some e-mails are stored from
http://www.heise.de/security/dienste/Emailcheck-2109.html

**Comment by Neo23x0** [comment]
rule adjusted
