### ISSUE TITLE
Bitdefender dll generates false positive

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/Loki#122]
Two warnings (score 80)  were triggered for Bitdefender dll file, bacause the file met a yara rule. The file was uploaded to VirusTotal, CrowdStrike Falcon and MetaDefender and appeared as clean.

Details:

Alert Filescan Malicious file found
FILE: C:\Program Files\Bitdefender\Bitdefender Security\ctc\ctc_00014_002\ctc.dll SCORE: 80
MD5: 7d485dcf1a51aaca2a30a36a1ed7c7d5
SHA1: aee2619248b60b6edd8f80f9c3c1e0da30de00ce
SHA256: 99861ea2d2a8c723319856007d93ae113579ad4d152d27ecda8a5795d8e06bd2
SIZE: 733952 TYPE: UNKNOWN FIRSTBYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
CREATED: 2019-05-07T12:00:53Z MODIFIED: 2019-05-07T12:00:54Z ACCESSED: 2019-05-07T12:00:54Z EXT: .dll
REASON_1: YARA rule lsadump / LSA dump programe (bootkey/syskey) - pwdump and others MATCHED_1: Str1: "\domains\account" SUBSCORE_1: 80 REF_1: not set
Alert Filescan Malicious file found
FILE: C:\Program Files\Bitdefender\Bitdefender Security\ctc\ctc_00015_003\ctc.dll SCORE: 80
MD5: 55029462b7cf9bde2b9971e71ba0a0e1
SHA1: 783bc257db55768042d7f579aa0dd8d5ca2cc07e
SHA256: 8923e1eaf2373e79ab2183a42629f6befc46ff689fbdbbbefab55c46d6c36877
SIZE: 733952 TYPE: UNKNOWN FIRSTBYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
CREATED: 2019-05-09T10:47:44Z MODIFIED: 2019-05-09T10:47:44Z ACCESSED: 2019-05-09T10:47:44Z EXT: .dll
REASON_1: YARA rule lsadump / LSA dump programe (bootkey/syskey) - pwdump and others MATCHED_1: Str1: "\domains\account" SUBSCORE_1: 80 REF_1: not set

**Comment by Neo23x0** [comment]
Thanks. Fixed that.
