### ISSUE TITLE
false negative detection

### ISSUE THREAD

**Issue by Q7ak5** [Neo23x0/Loki#126]
An ISO image triggered Bitdefender Total Security 2019, the message was that a file in the image was labeled as: "Trojan.Linux.Generic.13129", no other security package issued an alarm. The file was exfiltrated from the iso image and sent to Bitdefender labs for further investigation. They confimred today that it is malware, the SH256: 6acabe9771d66Oaa3d6d17a4O3d2f67fbc418682f9497O617ee6eOb4ca9128e9
It is possible to sent the file als password secured rar archive to you, if you provide an e-mail address for replying.

**Comment by Neo23x0** [comment]
How is this related to LOKI?

**Comment by Neo23x0** [comment]
And why does the SHA256 hash contain `O` characters? 
I changed them to `0` and found this on VT
https://www.virustotal.com/gui/file/6acabe9771d660aa3d6d17a403d2f67fbc418682f94970617ee6e0b4ca9128e9/detection

It seems to be `pnscan`, a port scanner for Linux. 
https://github.com/ptrrkssn/pnscan

**Comment by Q7ak5** [comment]
I used SPARK Core, no detection of the file. SPARK Core comments should be also posted under LOKI. Yes, you are right, the file in question is a pnscan (it belonged to an ISO image of a larger bundle). But the file was sent to Bitdefender lab for further investigations. They confirmed today it is malware and refused to consider it as a false positive detection. I did not get any further details about the malware detected. Therefore, I cannot comment it further. I can only offer you to send you the file for clarification.

**Comment by Neo23x0** [comment]
It isn't malware but a hack tool, like nmap or ncat. AV engines typically don't flag this. They try to cover this type of threat in PUAs (Potentially Unwanted Applications) or PUP / PUS (programs, software). 

LOKI and SPARK don't scan ISO files. I'll add a signature with score 50.

**Comment by Q7ak5** [comment]
I know that AV engines label hacking tools sometimes as PUA, e.g. nmap and others are were not labeled as PUA by Bitdefender. But the file in question was labeled as generic trojan. So I sent it to Bitdefender and asked them whether it could may be a false positive detection. Because I am aware about the fact, that hacking tools could may trigger them. They wrote today in an e-mail regarding the submission: "Wir haben den Rapport vom Labor zurückbekommen, die Beispiel-Datei wird als Malware korrekt erkannt und die Malware-Erkennung wird also bleiben." Commonly they make a distinction between PUA and malware.
I do not have more information than that. However, if you are sure it is only a PUA and not a malware, I agree to withdraw my statement as irrelevant.
