### ISSUE TITLE
Triton Actor TTP IOCs - cryptopp.dll

### ISSUE THREAD

**Issue by d-coddington** [Neo23x0/Loki#128]
Getting alerts on the below. Looks like the malware hashes are pulled from the IOCs section of the FireEye link in the alert. The problem is that both hashes listed in the alert (and FireEye linkl) are for a valid copy of CRYPTOPP.DLL.

FILE: M:\Program Files (x86)\Microsoft Office\Office12\CRYPTOPP.DLL SCORE: 100 TYPE: EXE SIZE: 1277496
FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
MD5: 9a7234078559093e06c9d32148ed95a3
SHA1: 40361dad15b9b5ae2757a21d1ce6a61c3c37e891
SHA256: 32f5d0a454c26e8aa6f4cad58f3782337cc97cfe2305bbfe564437e5f0d51bbc CREATED: Wed Sep 13 09:09:18 2006 MODIFIED: Wed Sep 13 09:09:18 2006 ACCESSED: Tue Jul 10 10:52:28 2018
REASON_1: Malware Hash TYPE: SHA256 HASH: 32f5d0a454c26e8aa6f4cad58f3782337cc97cfe2305bbfe564437e5f0d51bbc SUBSCORE: 100 DESC: Triton Actor TTP IOCs - cryptopp.dll - https://www.fireeye.com/blog/threat-research/2019/04/triton-actor-ttp-profile-custom-attack-tools-detections.html

**Comment by Neo23x0** [comment]
Fixed
