### ISSUE TITLE
Output -- machine analyzable

### ISSUE THREAD

**Issue by davehull** [Neo23x0/Loki#13]
Could you add functionality to loki to have it produce output that a machine can analyze? For instance, csv, tsv or json, such that results from hundreds of systems can be written to a database and queried?

**Comment by Neo23x0** [comment]
STDOUT or file output?

**Comment by Neo23x0** [comment]
I added the --csv option in version 0.9.1 that I pushed some seconds ago. Please check if that is what you were looking for.

**Comment by davehull** [comment]
Perfect! Thanks for the quick turn around.
