### ISSUE TITLE
Feature Request - Colorized HTML Log Output

### ISSUE THREAD

**Issue by SeattleForensics** [Neo23x0/Loki#143]
I ran into a situation, running LOKI with --intense on a machine infected with ransomware. There was so much output from LOKI, that I could not scroll back to see everything in the cmd window. The red color is a great visual queue, and the log file itself reviewed in NotePad++ made it difficult to find those important items. Even in CSV mode, Excel doesn't always line everything up because some rules are more verbose than others, and therefore have more columns, so sorting and filtering doesn't always get me where I want for easy review either. 

If there was color coded HTML output, to match what is seen in the command window, I feel like that would make review easier when there is a large volume of log ouput. It this a possibility? Is there perhaps a different workflow I could use to more easily review the high priority items when there are so many that scroll-back is not possible?

**Comment by Neo23x0** [comment]
I will not add this to LOKI. 
I've already developed such a report in THOR and THOR Lite. I, myself won't do that in this project.
