### ISSUE TITLE
Cannot directly run loki.exe on Ubuntu 16.04. Pre-requirements?

### ISSUE THREAD

**Issue by li-xin-yi** [Neo23x0/Loki#146]
I download the release of  [LOKI version 0.30.7](https://github.com/Neo23x0/Loki/releases) and extract all files on Ubuntu 16.04. But I cannot execute the `loki.exe` in it. Do I need to install any other dependencies? 

![image](https://user-images.githubusercontent.com/10118462/83935046-9fb1b780-a783-11ea-8201-3c94ae6ce60e.png)

**Comment by li-xin-yi** [comment]
Though, I can clone the whole repo and use Python 2.7 to run `loki.py`. I don't think it is a good idea to include only `.exe` in the public release. You'd better consider platforms on which it is going to be installed, at least, more detailed instruction for installing should be given.

**Comment by Neo23x0** [comment]
Yes, there is no precompiled binary for Linux or macOS systems. 

We provide THOR Lite with pre-compiled binaries here: 
https://www.nextron-systems.com/thor-lite/
