### ISSUE TITLE
Fetch data from MISP (Malware Information Sharing Platform)

### ISSUE THREAD

**Issue by elhoim** [Neo23x0/Loki#15]
[MISP](https://github.com/MISP/MISP) is a platform to echange IOCs.

MISP has a key-authenticated REST API available, there is some documentation in [this file](https://github.com/MISP/MISP/blob/master/INSTALL/documentation.pdf), and a reference library implementation in python: [PyMISP](https://github.com/CIRCL/PyMISP).

Existing MISP data types that might be of interest to be used for lookups: yara, filename, mutex, md5, sha1, sha256, email subject, email attachment. [New data types](https://github.com/MISP/MISP/issues/460) to be implemented in the future: URI-regexp, filename-regexp, SSL certificates attributes.

I can arrange access to a MISP instance hosting IOCs if you need it for testing.

**Comment by Neo23x0** [comment]
Access to MISP instance would be useful. 
I can integrate some of the IOC types: yara, filename, md5, sha1, sha256, filename-regexp

I'll create a downloader that pulls the IOCs from the MISP and stores them in an appropriate LOKI signature format.

**Comment by elhoim** [comment]
You will receive an email soon from circl.lu people... :)

**Comment by Neo23x0** [comment]
First version is included - see the "./threatintel" subfolder
