### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0418' in position 37: ordinal not in range(128)

### ISSUE THREAD

**Issue by willofr** [Neo23x0/Loki#162]
Hi folks,

while i was scanning a Centos 7 VM, i faced a python exception during file scan:

>|Traceback (most recent call last):
>  File "loki.py", line 1622, in <module>
>    loki.scan_path(defaultPath)
>  File "loki.py", line 203, in scan_path
>    for root, directories, files in os.walk(unicode(path), onerror=walk_error, followlinks=False):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/os.py", line 294, in walk
>    for x in walk(new_path, topdown, onerror, followlinks):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/os.py", line 294, in walk
>    for x in walk(new_path, topdown, onerror, followlinks):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/os.py", line 294, in walk
>    for x in walk(new_path, topdown, onerror, followlinks):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/os.py", line 294, in walk
>    for x in walk(new_path, topdown, onerror, followlinks):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/os.py", line 294, in walk
>    for x in walk(new_path, topdown, onerror, followlinks):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/os.py", line 284, in walk
>    if isdir(join(top, name)):
>  File "/home/vagrant/Loki/venv/lib64/python2.7/genericpath.py", line 41, in isdir
>    st = os.stat(s)
>UnicodeEncodeError: 'ascii' codec can't encode character u'\u0418' in position 37: ordinal not in >range(128)

I tried to execute loki with --debug and --printall option, but i can't find out which directory or file could generate this exception.

Any idea how to spot the directory/file causing this ? 

Thank you.

**Comment by negrusti** [comment]
Possibly related - Loki crashes for me on one file with

```
Traceback (most recent call last):
  File "loki.py", line 1622, in <module>
    loki.scan_path(defaultPath)
  File "loki.py", line 203, in scan_path
    for root, directories, files in os.walk(unicode(path), onerror=walk_error, followlinks=False):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf9 in position 3: invalid start byte

```

**Comment by Neo23x0** [comment]
What do you try? Build it?
You don't use the prebuild executable from the release section?

**Comment by Neo23x0** [comment]
You're using it on Linux? Okay, first Linux user of LOKI 0.40+. 
"helpers" is an internal module. Somehow it cannot find the module in the sub folder.

**Comment by Neo23x0** [comment]
I'Ve fixed some requirements but my version runs just fine on Debian 10 with Python 3.7.3 

https://github.com/Neo23x0/Loki/commit/d79252d367743d1406f172288ad3cd3d69927048

![Screenshot 2021-03-11 at 12 12 44](https://user-images.githubusercontent.com/2851492/110778893-37888880-8263-11eb-97b4-caf43f18b26c.png)

Are you sure you've used the `py3` branch and used `python3`?

**Comment by negrusti** [comment]
@Neo23x0 Debian 10 as well. Used python3 but wasn't aware about py3 branch. Will re-test

**Comment by negrusti** [comment]
now running (py3 0.40.0) but shows lots of errors at the beginning:
```
RROR] Error while initializing Yara rule crime_trickbot.yar ERROR: line 52: invalid field name "imphash"
Traceback (most recent call last):
  File "loki.py", line 1107, in initialize_yara_rules
    'md5': dummy,
yara.SyntaxError: line 52: invalid field name "imphash"                                                                                                                                    [ERROR] Error while initializing Yara rule apt_exile_rat.yar ERROR: line 22: invalid field name "imphash"
Traceback (most recent call last):
  File "loki.py", line 1107, in initialize_yara_rules
    'md5': dummy,
yara.SyntaxError: line 22: invalid field name "imphash"                                                                                                                                    [ERROR] Error while initializing Yara rule gen_icon_anomalies.yar ERROR: line 65: invalid field name "number_of_signatures"
Traceback (most recent call last):
  File "loki.py", line 1107, in initialize_yara_rules
    'md5': dummy,
yara.SyntaxError: line 65: invalid field name "number_of_signatures"                                                                                                                       [ERROR] Error while initializing Yara rule apt_silence.yar ERROR: line 58: invalid field name "imphash"
Traceback (most recent call last):
  File "loki.py", line 1107, in initialize_yara_rules
    'md5': dummy,
yara.SyntaxError: line 58: invalid field name "imphash"                                                                                                                                    [ERROR] Error while initializing Yara rule apt_cmstar.yar ERROR: line 26: invalid field name "imphash"
Traceback (most recent call last):
  File "loki.py", line 1107, in initialize_yara_rules
    'md5': dummy,
yara.SyntaxError: line 26: invalid field name "imphash"
```

**Comment by Neo23x0** [comment]
It's a YARA issue caused by a compilation without OpenSSL. 

See
https://github.com/VirusTotal/yara-python/issues/119
https://github.com/VirusTotal/yara-python/issues/97

**Comment by Neo23x0** [comment]
![Screenshot 2021-03-11 at 19 06 17](https://user-images.githubusercontent.com/2851492/110833667-fb721980-829c-11eb-9c0a-ad37207f2d91.png)
😄
