### ISSUE TITLE
question about dependencies 

### ISSUE THREAD

**Issue by questionanswerguy** [Neo23x0/Loki#163]
hello,
im trying to build a .exe file from source code for windows 10 but i keep getting into problems with version incompatibility 
for example what python version you guys are using? if it was 2.7.18 then that is not compatible with latest release of yara-python which is version 4.0.4 so i had to downgrade to 3.5 in order for it to work with python 2.7.18 also pyinstaller version 2.1 doesnt work it keeps giving me a syntax error.

sooo here is my question what is exactly the version of dependencies you guys are using to build a .exe for loki?
and what version of windows are you guys using?

i tried build it using the latest release source code which is version 0.33.0

- python version == ??
- netaddr version == ??
- psutil version == ??
- pylzma version == ??
- yara-python version == ??
- colorama version == ??
- rfc5424-logging-handler version = ??
- pycrypto version == ??
- wmi version == ??
- pywin32 version == ??
- setuptools version == ??
- pyinstaller version == ??

**Comment by 2d4d** [comment]
here's a version which runs with python3, maybe try that: https://github.com/2d4d/Loki

**Comment by 2d4d** [comment]
pls try https://github.com/Neo23x0/Loki/releases/tag/0.40b

**Comment by questionanswerguy** [comment]
> pls try https://github.com/Neo23x0/Loki/releases/tag/0.40b

Will do but question, is there a reason on removing private signatures encryption and packaging from this branch?
Cause i dont see it referenced in read.me file

**Comment by Neo23x0** [comment]
> Will do but question, is there a reason on removing private signatures encryption and packaging from this branch?

Don't want to support it anymore. Too many problematic dependencies.
