### ISSUE TITLE
python3 build error and fix

### ISSUE THREAD

**Issue by mikkel0x** [Neo23x0/Loki#170]
ISSUE: Noticed the py3 branch is still failing when building with python3 ./loki.py. The updater is calling for python. 

FIX: Add `python3` to line 1380. 

`# Updater 
    if os.path.exists(os.path.join(get_application_path(), 'loki-upgrader.exe')) and os_platform == "windows":
        pArgs.append('loki-upgrader.exe')
    elif os.path.exists(os.path.join(get_application_path(), 'loki-upgrader.py')):
        pArgs.append('python3')
        pArgs.append('loki-upgrader.py')
    else:
        logger.log("ERROR", "Update", "Cannot find neither thor-upgrader.exe nor thor-upgrader.py in the current workign directory.")`

**Comment by deeagle** [comment]
As Workaround, you can call `loki-upgrader` with the `python`-param from loki itself and set the interpreter location, e.g. `python3 loki.py --python /usr/bin/python3 --update`

seems to work for me
