### ISSUE TITLE
ERROR: 'charmap' codec can't decode byte 0x9d in position 280: character maps to <undefined>

### ISSUE THREAD

**Issue by mayben0x** [Neo23x0/Loki#171]
This error keeps on coming up. Before its working fine. Any idea how to fix this? tried a lot of ways but still not working

**[ERROR] Error reading signature file D:\Downloads\loki_0.41.0\loki\signature-base\yara\ab_webshell.yar ERROR: 'charmap' codec can't decode byte 0x9d in position 280: character maps to <undefined>**
[INFO] Initializing all YARA rules at once (composed string of all rule files)
[INFO] Initialized 739 Yara rules

YARA Rule causing an error:

rule webshell_test {
  meta:
        author = “”
        date = “”
        description = “”
 
 strings:

        $s1 = “ba42se64_enc4242ode”
        $s2 = “gz42unco42mpress” 
	$s3 = "fi42le_get_contents"

 condition:
        any of ($s*) or
        all of ($s*)
        filesize < 1KB
}

**Comment by Neo23x0** [comment]
I don't know that rule. There is no ab_webshell.yar rule in that folder.

**Comment by Neo23x0** [comment]
BTW that rule contains non-ASCII characters in form of Unicode upper ticks.

**Comment by mayben0x** [comment]
> I don't know that rule. There is no ab_webshell.yar rule in that folder.

I created that rule. I have other ruleset that i created and copied in the signature-base folder and they are working fine except for this :(  what modification should i do since the strings that i wanted to look for are non-ascii?

**Comment by mayben0x** [comment]
That's what i used " there is no other " in the keyboard =P

**Comment by mayben0x** [comment]
finally FIXED the problem but not using any " =P
