### ISSUE TITLE
.yar files detected as malware

### ISSUE THREAD

**Issue by B321321** [Neo23x0/Loki#175]
Microsoft defender and clouud tools detects these files gen_webshells.yar and thor-webshells.yer as these malware respectively PHP/Remoteshell.G and PHP/Dirtelti.CKB

**Comment by hitem** [comment]
Yes, the yara files are not compiled and thus all AV's will detect some of them as malware (as the AV's do have their own detections for the same hash and/or other indicators). Would be nice if we could run loki with compiled rules? :)

**Comment by Neo23x0** [comment]
Defender Issue
