### ISSUE TITLE
Probably FP in this case

### ISSUE THREAD

**Issue by gunnersson** [Neo23x0/Loki#18]
```
20150902T00:10:25Z MR_WHISPER LOKI: Malware Hash TYPE: MD5 HASH: b8a9e91134e7c89440a0f95470d5e47b FILE: C:\maxima-5.37.0\bin\zlib1.dll DESC: LusyPOS http://securitykitten.github.io/lusypos-and-tor/
```
please, refer to 
https://en.wikipedia.org/wiki/Maxima_%28software%29
http://sourceforge.net/projects/maxima/

**Comment by gunnersson** [comment]
https://www.virustotal.com/de/file/42967a768f341d9ce5174eb38a4d63754c3c41739e7d88f4e39cd7354c1fac71/analysis/

**Comment by Neo23x0** [comment]
Thanks and sorry for the delay - Added the hash to falsepositive-hashes.txt
