### ISSUE TITLE
Loki not detecting "exe"

### ISSUE THREAD

**Issue by viks2015** [Neo23x0/Loki#19]
1.  I have created yara rules for some "exe" and also put the HASH of the file in hash-iocs.txt but LOKI fails to detect it.

2. The exe file is created using py2exe and when I run loki with debug mode, it is confirmed that loki is ignoring this exe file and not hashing it.

3. You can try the same with LOKI.exe since it is also made with py2exe

4. Same could also be the problem with your thor apt scanner.

**Comment by Neo23x0** [comment]
How big is your file. 
It doesn't check files bigger than 2048kb by default:

  -s kilobyte     Maximum file size to check in KB (default 2048 KB)

**Comment by viks2015** [comment]
Thanks for reply. the file size is about 6MB. 
It is working now with the -s flag
