### ISSUE TITLE
Unable to scan multiple drives in one go

### ISSUE THREAD

**Issue by Mytre** [Neo23x0/Loki#192]
I ran loki in a computer with multiple drives, only providing parameters for the log file output. THe scanner only scanned C drive and did not scan D, E ,F or any other subsequent drive.  

Is this expected behaviour? if so can one specify multiple drives to scan?

**Comment by Neo23x0** [comment]
https://github.com/Neo23x0/Loki/releases/tag/0.44.0

**Comment by Neo23x0** [comment]
Is there a reason why you don't use the more advanced THOR Lite?
https://www.nextron-systems.com/thor-lite/

**Comment by Mytre** [comment]
> 
> 
> Is there a reason why you don't use the more advanced THOR Lite?
> https://www.nextron-systems.com/thor-lite/

I was not aware of this at all ! thank you very much also for the Loki update.
