### ISSUE TITLE
False positive: Oracle Virtual Box

### ISSUE THREAD

**Issue by tsturzenegger** [Neo23x0/Loki#2]
Hi,

Thanks for the tool!

I think i got a false positive: 

[ALERT] Yara Rule MATCH: WaterBug_ComRat FILE: C:\Program Files\Oracle\VirtualBox\VBoxSharedCrOpenGL.dll

https://www.virustotal.com/en/file/9fd7b6df8c3e59838af2fc66984f196a6144ad364e44b45733313a24e0f55785/analysis/1422375644/

The software is the recent version of Oracle Virtual Box

Kind regards
Tobias

**Comment by Neo23x0** [comment]
Thanks - I took the rule directly from the Symantec report appendix. 
Disabled rule as it triggered other false positives as well.
