### ISSUE TITLE
Wireguard generates a warning

### ISSUE THREAD

**Issue by s482dcaw** [Neo23x0/Loki#200]
Hi
I assume this is a false positive you need to exclude

[WARNING] PE-Sieve reported implanted process PID: 4988 NAME: wireguard.exe OWNER: SYSTEM CMD: "C:\Program Files\WireGuard\wireguard.exe" /managerservice PATH: C:\Program Files\WireGuard\wireguard.exe IMPLANTED PE: 2 IMPLANTED SHC: 0
[INFO] Scanning Process PID: 5036 NAME: wireguard.exe OWNER: SYSTEM CMD: "C:\Program Files\WireGuard\wireguard.exe" /tunnelservice "C:\Program Files\WireGuard\Data\Configurations\configuration.dpapi" PATH: C:\Program Files\WireGuard\wireguard.exe
[WARNING] PE-Sieve reported implanted process PID: 5036 NAME: wireguard.exe OWNER: SYSTEM CMD: "C:\Program Files\WireGuard\wireguard.exe" /tunnelservice "C:\Program Files\WireGuard\Data\Configurations\configuration.dpapi" PATH: C:\Program Files\WireGuard\wireguard.exe IMPLANTED PE: 1 IMPLANTED SHC: 0

**Comment by Neo23x0** [comment]
That's okay
