### ISSUE TITLE
Few FP's

### ISSUE THREAD

**Issue by ndrix** [Neo23x0/Loki#21]
* MD5 e617348b8947f28e2a280dd93c75a6ad is detected as "The Net Traveler" malware, but any new , empty, Ms Word Document will create this hash. (https://www.virustotal.com/en/file/06f7826c2862d184a49e3672c0aa6097b11e7771a4bf613ec37941236c1a8e20/analysis/)

* 0d4c486a24a711a45fd83acdf4d18506 and ca0c67ba7aeba6aed5ddb852e6eea811is detected as a fake Adobe Flash program (based on strings), but it's legitimate (https://www.virustotal.com/en/file/df72d035b31b1ff89f752e83af14b9e9dcf4913d9954f074546860d10b6908fb/analysis/ - https://www.virustotal.com/en/file/1c52b50019786ce77c3338f470a9193f90f71080196198357744cb065b7c6851/analysis/)

Plus, it would also help that if a GIF files is "cloaked" as a JPG file, to not display it as a warning.  Some of the .NET framework images are saved wrongly (i.e: they are a GIF, but saved with the JPG extension).

If you want, I can update the IOC / hashes files, and issue a pull request?  The tool has been extremely useful otherwise!

Thanks, -m

**Comment by Neo23x0** [comment]
I put the hashes into falsepositive-hashes.txt

I'll add the following condition to the Cloaked_as_JPG rule:
and filetype != "GIF"

**Comment by ndrix** [comment]
Hi Florian, thank you for the update.  It's great software! Well done!

**Comment by Neo23x0** [comment]
Thanks, 

could you check if these fixes solved the problem for you? (if you have the samples and not just the log data from a analysed system)

**Comment by ndrix** [comment]
Will check it at the customer site again on Sunday and let you know
