### ISSUE TITLE
Error while extracting the signature files

### ISSUE THREAD

**Issue by eyaladmin** [Neo23x0/Loki#219]
Hi

I am using windows 11

And there is an issue with the signature update even when I try to take them with loki-upgrade command

c:\Program Files\Loki>loki-upgrader.exe --sigsonly --debug

  LOKI UPGRADER

[INFO] Updating Signatures ...
[INFO] Downloading https://github.com/Neo23x0/signature-base/archive/master.zip ...
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki-upgrader.py", line 90, in update_signatures
  File "http\client.py", line 471, in read
  File "http\client.py", line 614, in _safe_read
http.client.IncompleteRead: IncompleteRead(2930480 bytes read, 410558 more expected)
[ERROR] Error while extracting the signature files from the download package

What do you recommend to troubleshoot it?

Is there a way I can put the signature manually for the scan?

Thank you

**Comment by Neo23x0** [comment]
It's most likely your AV or EDR blocking the extraction

**Comment by eyaladmin** [comment]
Hi 
I already excluded "c:\Program Files\Loki" 
any other path is also part of the operation, such as temp folder or such?

**Comment by Neo23x0** [comment]
No. But it's your AV. I guess it's a module that checks HTTP/HTTPS traffic. It seems that the package download gets blocked.

**Comment by eyaladmin** [comment]
OK
I will look for it, thanks
Are there manual steps to update the signature by manually downloading the file and so on?

**Comment by Neo23x0** [comment]
The manual process would also be blocked by your AV, I guess

**Comment by Neo23x0** [comment]
You could try to download the whole [signature-base](https://github.com/Neo23x0/signature-base) repo as a ZIP package and then extract it into the program root folder

![image](https://user-images.githubusercontent.com/2851492/193410366-2068b391-b7ec-4358-80f0-053a98c57829.png)

![image](https://user-images.githubusercontent.com/2851492/193410362-1445f5a5-1421-4f37-80ee-3b95f9abbf65.png)

**Comment by eyaladmin** [comment]
Thanks for your help

the hash for the zip file is marked as a trojan
but scanning inside the extracted folder, all hashes are fine.

And an unimported note, scanning shows 0.44.2 shows 0.45

Not sure if this is because of the manual update or else

![Screenshot loki0 45](https://user-images.githubusercontent.com/61413950/193411726-bba8152f-5776-4b98-a811-8c1247bf798e.png)
