### ISSUE TITLE
windows 11 with office 2021 scan report unexpected file size OUTLOOK.EXE & wininit.exe

### ISSUE THREAD

**Issue by eyaladmin** [Neo23x0/Loki#220]
Hi

For your information only.
It could be that the Yara is not up to date with the latestt windows and office files.

The Virtus Total shows 0% detections
and the file is self-singed

Let me know if you need me to upload the files

about the "Directory walk error" in the picturerr, I think this path is too long to scan.

Thank you very much

![Screenshot 2022-10-09 134527](https://user-images.githubusercontent.com/61413950/194752444-6f0d8c21-9f98-4c23-8697-f1272542be7b.png)
![Screenshot 2022-10-09 134446](https://user-images.githubusercontent.com/61413950/194752446-6852e9c1-6017-470f-b103-f72aa014ab22.png)
![Loki Screenshot 2022-10-09 133947](https://user-images.githubusercontent.com/61413950/194752447-7c0ec163-3869-430d-a80e-41fe3ab8f74a.png)

**Comment by Neo23x0** [comment]
fixed with https://github.com/Neo23x0/signature-base/commit/dce55d6e708a44d070e232e7bca17a54646d4ae9
