### ISSUE TITLE
Loki scans whole C:/ even with path argument

### ISSUE THREAD

**Issue by notacodingweeb** [Neo23x0/Loki#225]
![34EAE3C8-1123-465D-AAA0-82F8A0FF6FD1](https://user-images.githubusercontent.com/100553943/203301308-be75aeed-ed60-4f2d-accb-25fee75cbd3c.jpeg)

This is the path that im trying to scan but it still scans C:// 

![ABD9B546-9168-4E18-931E-8933100D52B5](https://user-images.githubusercontent.com/100553943/203301469-915fbb69-faab-48a9-a4d3-a055545d8973.jpeg)

Any help is appreciated. Thank you

**Comment by Neo23x0** [comment]
This is the process check. You can use `--noprocscan` to skip that module.
