### ISSUE TITLE
Installing and running on Linux OS

### ISSUE THREAD

**Issue by cyborg1234** [Neo23x0/Loki#231]
Dear Sir/Madam,

I am interested in running the Loki application on Linux OS and is facing some issues so far (such as running .exe file on linux), and would like to receive some guidance and advice.

Thank you very much.

Yours Sincerely,
cyborg1234

**Comment by Neo23x0** [comment]
I don't recommend that. I'd use THOR Lite to do that. 
https://www.nextron-systems.com/thor-lite/
