### ISSUE TITLE
Module not Found rfc5424logging

### ISSUE THREAD

**Issue by KivancD** [Neo23x0/Loki#237]
Hello Im trying to install LOKI on kali linux however when I try to run loki via "python3 loki.py -p" ı get this error 
ModuleNotFoundError: No module named "rfc5424logging". I ran the command "pip install rfc5424-logging-handler"  but it didn't fix the error. I need help please

![Ekran Resmi 2023-06-12 13 10 09](https://github.com/Neo23x0/Loki/assets/73711350/c5293e4f-4890-4b38-a5b9-bac2ce0904f1)

**Comment by harshb-icpl** [comment]
yeah, also facing same issue.

**Comment by KivancD** [comment]
> 

did you find any solution for it ?

**Comment by 0x4hm3d** [comment]
try this pip install rfc5424-logging-handler

**Comment by c0m4r** [comment]
For some time now venv is a thing. 

```bash
git clone https://github.com/Neo23x0/Loki.git
cd Loki
python3 -m venv .
. bin/activate
pip3 install -r requirements.txt
python3 loki.py
deactivate
```

With modern distros and newer versions of Python you should be able to use it then referring to venv links, without the need of activating venv each time.

```
cd Loki
bin/python3 loki.py
```

Otherwise `. bin/activate` venv before running Loki and `deactivate` afterwards.

**Comment by za** [comment]
Hi @KivancD 

Are you still having this issue? What Kali linux version are you using?

I have installed Loki successfully on Kali, but the difference is, I created a separate Python environment: so Loki is running in its own environment. I am using virtualenv to create the Python environment.

```
$ virtualen .env
$ source .env/bin/activate
$ pip install colorama yara-python psutil rfc5424-logging-handler netaddr
$ python loki-upgrader.py
$ python loki.py
```

No sudo required to run Python.
