### ISSUE TITLE
Windows executable versus python?

### ISSUE THREAD

**Issue by Danconnolly** [Neo23x0/Loki#24]
When I run loki.exe it doesnt check wininit.exe (used --debug, no trace of any check of wininit.exe). 

When I use "python loki.py", same arguments ("-p C:\Windows\System32 --noprocscan --printAll --debug"), it does check wininit.exe and report suspicious because its too large (which probably needs an update). 64-bit Python 2.7.

Both cases run from administrative level command line, on 64-bit up-to-date Windows 10.

**Comment by Neo23x0** [comment]
The Executable is a x86 program. 
If you point it at System32 it will be automatically (by Windows itself) redirected to Sysnative. 

Check
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187(v=vs.85).aspx

You 64bit Python directly accesses the wininit.exe in the System32 folder. The 32-bit executable will see a different directory when pointed to System32. 

I recently committed some changes on file size in Windows 10. 
https://github.com/Neo23x0/Loki/commits/master

Could you please send me the size in bytes of the wininit.exe in you installation?

**Comment by Danconnolly** [comment]
Thanks, good and comprehensive explanation.

290,856 bytes
Signature looks valid, dated ‎Friday, ‎October ‎30, ‎2015 4:17:36 AM

LOKI: MD5: cad491dd9ec00bb841ea407d9c498c4a SHA1: 09461fb4641fcef554341bb8d198357a2d988e62 SHA256: fc64cdfd7292d60ec4cdc70225809656e0feb19eca49d84accd1f480cab77590 FILE: C:\Windows\System32\wininit.exe

https://www.virustotal.com/en/file/fc64cdfd7292d60ec4cdc70225809656e0feb19eca49d84accd1f480cab77590/analysis/

File looks legit.

**Comment by Neo23x0** [comment]
Ok, fixed. 
Thanks for the report and details.
