### ISSUE TITLE
Error while initializing Yara rule thor_inverse_matches.yar 

### ISSUE THREAD

**Issue by BirzhanTazhibayev** [Neo23x0/Loki#251]
[ERROR] Error while initializing Yara rule thor_inverse_matches.yar ERROR: line 554: syntax error
Traceback (most recent call last):
  File "loki.py", line 1136, in initialize_yara_rules
    compiledRules = yara.compile(source=yara_rule_data, externals={
yara.SyntaxError: line 554: syntax error

**Comment by Neo23x0** [comment]
oh, boy.
