### ISSUE TITLE
Customized Path

### ISSUE THREAD

**Issue by newrealforce9499** [Neo23x0/Loki#255]
Hello
i am trying to use Memprocfs along with loki whenever i give it the path as this
loki.exe -p "Q:\pid" --force --csv --logfolder "C:\Users\xxxxx\Downloads\loki_0.51.0\loki\loggy" --printall --allreasons --intense --vulnchecks --scriptanalysis > C:\Users\xxxxx\Downloads\loki_0.51.0\loki\loggy\scan_results.csv
eventhough Q:\pid is valid directory but loki keeps scanning my system?
why?

Regards, Naser

**Comment by Neo23x0** [comment]
Did you read the "Important Note" in the README? 

You have to disable the process check with `--noprocscan` to run only the file system scan.

**Comment by newrealforce9499** [comment]
sadly, my bad
sorry
regards , Naser

**Comment by newrealforce9499** [comment]
executing the following command would not show any progress percentage or bar
loki.exe -p "Q:\pid" --force --csv --logfolder "C:\Users\xxxxx\Downloads\loki_0.51.0\loki\loggy" --onlyrelevant --allreasons --intense --vulnchecks --scriptanalysis > C:\Users\xxxxx\Downloads\loki_0.51.0\loki\loggy\scan_results.csv
