### ISSUE TITLE
FP: javac.exe

### ISSUE THREAD

**Issue by 1337hax** [Neo23x0/Loki#26]
Detection message (in red color):
[ALERT] File Name IOC matched PATTERN: \\javac\.exe DESC: Hexacorn Blog Entry -
Homomorphic abuse http://goo.gl/1UGJVn MATCH: C:\Program Files\Java\jdk1.8.0_20\
bin\javac.exe

I've uploaded this file to virustotal and got 0/54. It's legit javac.exe file, probably it should by whitelisted or something. I think it's detected only by filename.

**Comment by Neo23x0** [comment]
Removed from list - thanks
