### ISSUE TITLE
FP: starter.exe from Eclipse

### ISSUE THREAD

**Issue by 1337hax** [Neo23x0/Loki#27]
Detection message (in red):
[ALERT] File Name IOC matched PATTERN: \\starter\.exe$ DESC: ThreatExpert Statistics MATCH: C:\Users\myusername\Documents\eclipse-cpp-luna-R-win32-x86_64\eclipse\plugins\org.eclipse.cdt.core.win32.x86_64_5.3.0.201406111759\os\win32\x86_64\starter.exe

Link to virustotal scan (0 / 54): https://www.virustotal.com/en/file/62418c2021041d098de17bbb94fb15ed8e120f6585da93a5ac2ab17dcd733bed/analysis/1453155432/

**Comment by Neo23x0** [comment]
Fixed. Thanks!
