### ISSUE TITLE
Loki 3.4 - some false positives

### ISSUE THREAD

**Issue by gunnersson** [Neo23x0/Loki#3]
Dear all,

recently used *Loki 3.4* and its signature files from 2015-02-18. The log shows some *File Name Suspicious IOC matched PATTERN*. They are obviously false positives...

> Feb 19 01:33:17 MR_WHISPER LOKI: Scanning C:\ ...  
> Feb 19 01:38:59 MR_WHISPER LOKI: File Name Suspicious IOC matched PATTERN: \.XOR DESC: Symantec Waterbug Attack http://goo.gl/9Tlk90 MATCH: C:\Program Files (x86)\CrypTool 2\OnlineDocumentation\Components\Cryptool.XOR.Xor.png
> Feb 19 01:38:59 MR_WHISPER LOKI: File Name Suspicious IOC matched PATTERN: \.XOR DESC: Symantec Waterbug Attack http://goo.gl/9Tlk90 MATCH: C:\Program Files (x86)\CrypTool 2\OnlineDocumentation\Components\Cryptool.XOR.Xor_de.html
> Feb 19 01:38:59 MR_WHISPER LOKI: File Name Suspicious IOC matched PATTERN: \.XOR DESC: Symantec Waterbug Attack http://goo.gl/9Tlk90 MATCH: C:\Program Files (x86)\CrypTool 2\OnlineDocumentation\Components\Cryptool.XOR.Xor_en.html
> Feb 19 01:39:10 MR_WHISPER LOKI: File Name Suspicious IOC matched PATTERN: \.XOR DESC: Symantec Waterbug Attack http://goo.gl/9Tlk90 MATCH: C:\Program Files (x86)\CrypTool 2\OnlineDocumentation\Templates\Cryptography.Classic.XOR.png
> Feb 19 01:39:10 MR_WHISPER LOKI: File Name Suspicious IOC matched PATTERN: \.XOR DESC: Symantec Waterbug Attack http://goo.gl/9Tlk90 MATCH: C:\Program Files (x86)\CrypTool 2\OnlineDocumentation\Templates\Cryptography.Classic.XOR_de.html
> Feb 19 01:39:10 MR_WHISPER LOKI: File Name Suspicious IOC matched PATTERN: \.XOR DESC: Symantec Waterbug Attack http://goo.gl/9Tlk90 MATCH: C:\Program Files (x86)\CrypTool 2\OnlineDocumentation\Templates\Cryptography.Classic.XOR_en.html
> Feb 19 02:43:40 MR_WHISPER LOKI: SUSPICIOUS OBJECTS DETECTED!
> Feb 19 02:43:40 MR_WHISPER LOKI: Loki recommends a deeper analysis of the suspicious objects.

The marked files belong to [CrypTool 2] (https://www.cryptool.org/de/), [Wikipedia: CrypTool] (https://de.wikipedia.org/wiki/CrypTool).

Thank you, gunnersson

**Comment by Neo23x0** [comment]
Ok, thank you - I fixed it by using 
\.XOR$
instead of 
\.XOR
in the regular expression.
