### ISSUE TITLE
False Positive (vshost)

### ISSUE THREAD

**Issue by SoKoSensei** [Neo23x0/Loki#33]
LOKI: File Name IOC matched PATTERN: \\vshost\.exe DESC: Hexacorn Blog Entry - Homomorphic abuse http://goo.gl/1UGJVn MATCH: C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\vshost.exe

SHA256: 07470371b6c705a49965ae5d98e26450b9fef50e4ba4851de91e29e9721ab197
This is legit MS file.

**Comment by Neo23x0** [comment]
Thanks for reporting back. 
Remove from signature-base

**Comment by Neo23x0** [comment]
Thanks for reporting back. 
Remove from signature-base
