### ISSUE TITLE
get-otx-iocs.py missing

### ISSUE THREAD

**Issue by orenelim** [Neo23x0/Loki#34]
Cannot find the get-otx-iocs.py script mentioned
Also the /threatintel is missing

Remark:
You need to create a folder named iocs under the signature-base folder otherwise the util crash under windows...
And there is a reference to /signature-base/misc/file-type-signature file

A file structure example would be very helpfull

**Comment by Neo23x0** [comment]
I recently integrated all signatures as sub-repository named "signature-base".
If you've download the LOKI repo as ZIP, the sub-repo is not included.

https://github.com/Neo23x0/signature-base

You can either download the sub-repo "signature-base" as ZIP and unpack it into the "/signature-base" subfolder or just clone the LOKI repo. 
I'll add that info to the README.

**Comment by orenelim** [comment]
Thank you for the prompt reply
And thank you for a very interesting tool!
Regards from Israel
Und
Viel spass

אורן אלימלך
יועץ סייבר, אבטחת-מידע, רגולציה, IT, תקשורת, פורנזיקה וענן
CISO, CISM, CISA, CISSP
+972-50-5375385
Oren Elimelech
Cyber Security, IS, GRC, ICT, Forensics & Cloud Consultant
CISO, CISM, CISA, CISSP
+972-50-5375385
