### ISSUE TITLE
launch on Linux

### ISSUE THREAD

**Issue by philoo9999** [Neo23x0/Loki#37]
Hi 

seems to be broken on linux with python 3.4
![2016-04-18_12-35-36](https://cloud.githubusercontent.com/assets/7375562/14601425/4d7974c0-0562-11e6-9952-0f26dfdb4ad9.png)

any idea ?

**Comment by Neo23x0** [comment]
It's written for Python 2.
Use Python 2.7 to run it.

**Comment by philoo9999** [comment]
fantastic it worked. :)
