### ISSUE TITLE
Doesn't recursively scan a mounted filesystem

### ISSUE THREAD

**Issue by jpoling-dswrx** [Neo23x0/Loki#38]
When issued against a mount point of a mounted filesystem, Loki only scans the files in the top-level directory and no subdirectories...

`sudo python loki.py -l ../LokiScan__root.log --noprocscan --intense --debug -p /mnt/filesystem_root/`

Skips all sub-directories and only scans the "." files in the root of the /mnt/filesystem_root/ directory.

**Comment by Neo23x0** [comment]
Does this subdirectory only contain symbolic links?

**Comment by jpoling-dswrx** [comment]
Nope, regular file system. Image taken of separate machine, root filesystem mounted to this system at /mnt/filesystem_root/.

**Comment by jpoling-dswrx** [comment]
It scans a separately mounted /tmp filesystem with various regular files mounted at /mnt/filesystem_tmp/ just fine.

**Comment by jpoling-dswrx** [comment]
Any idears?

**Comment by jenhek** [comment]
Same issue here

**Comment by dssink** [comment]
It's a problem with the mtab parsing at https://github.com/Neo23x0/Loki/blob/53669fc1473da55beb2821997e38863a64a6d95b/lib/helpers.py#L118-L123
For example, using sshfs creates a line in mtab that looks like
`user@host:/ on /mount/point type fuse.sshfs (flags)`
which means that `options[1]` is the word `on`, which doesn't start with `/`, so it gets excluded.
As a quick hack, just comment out the pipe and call to the misbehaving function with `# | set(getExcludedMountpoints())` on 141 in loki.py and you should be good to go. 

https://github.com/Neo23x0/Loki/blob/53669fc1473da55beb2821997e38863a64a6d95b/loki.py#L141

**Comment by Neo23x0** [comment]
I've introduced a `--force` parameter to scan excluded folders

https://github.com/Neo23x0/Loki/commit/eece378c0059dec8755be7776d4f0545e272d056
