### ISSUE TITLE
Process crash

### ISSUE THREAD

**Issue by jane567** [Neo23x0/Loki#39]
Hi!
I found that process (python loki.py  or loki.exe) crashed  when processing yara rules and found cyrillic filename. Crash occured in proc scan_path  at line
`                            # Scan the read data
                            for (score, rule, description, matched_strings) in \
                                    self.scan_data(fileData, fileType, filename, filePath, extension, md5):
`
Can you fix this issue?
Thanks.

**Comment by Neo23x0** [comment]
Cannot reproduce, tried to fix this in 0.15.3

**Comment by jane567** [comment]
I'm so sorry!
 I forgot to say that in original script (loki.py) this error can't occur at all. It seems you just skip processing filenames in unicode. So I was forced to change your code a little to accomplish processing filenames in russian. See attached diff 
[loki.diff.txt](https://github.com/Neo23x0/Loki/files/243563/loki.diff.txt)

**Comment by Neo23x0** [comment]
Great, thanks. 
Could you generate a pull request on the loki.py, so that I can just accept it after testing?
Just click "Edit" on the "thor.py" file, then copy & paste the changed source code and then select "creat pull request".

**Comment by jane567** [comment]
I hope all done correct ..
