### ISSUE TITLE
Incorrect work if app started from dir with unicode char in name

### ISSUE THREAD

**Issue by jane567** [Neo23x0/Loki#44]
Hi Florian!
I found following issue:
if application started from dir with cyrillic chars result of scan is ALWAYS:  SYSTEM SEEMS TO BE CLEAN.

BUT
Some errors displayed  with --debug option:

```
Traceback (most recent call last):
  File "loki.py", line 206, in scan_path
    if self.app_path.lower() in filePath.lower():
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 39: ordinal not in range(128)
Traceback (most recent call last):
  File "loki.py", line 206, in scan_path
    if self.app_path.lower() in filePath.lower():
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 39: ordinal not in range(128)
Traceback (most recent call last):
  File "loki.py", line 206, in scan_path
    if self.app_path.lower() in filePath.lower():
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 39: ordinal not in range(128)
...
```

To reproduce issue:
put loki.py with into dir, for example, c:\локи
then run 
`python loki.py -p c:\test`
and 
`python loki.py -p c:\test --debug`

So in this case we got wrong result of scanning
Thanks

**Comment by jane567** [comment]
Add fix for get_application_path()

**Comment by jane567** [comment]
fix not allpied to master

**Comment by SaiGonSeamus** [comment]
Is this the same issue?

  File "loki.py", line 1399, in <module>
    loki.scan_path(defaultPath)
  File "loki.py", line 172, in scan_path
    for root, directories, files in os.walk(unicode(path), onerror=walk_error, followlinks=False):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

**Comment by jane567** [comment]
It seems no

**Comment by Neo23x0** [comment]
Shouldn't be a problem anymore with the py3 version or use THOR Lite
