### ISSUE TITLE
equation group false positive

### ISSUE THREAD

**Issue by gretty** [Neo23x0/Loki#50]
Appears may have a false positive.  The hashes in the output for Yara Rule MATCH: EquationDrug_HDDSSD_Op TYPE: UNKNOWN DESCRIPTION: EquationDrug - HDD/SSD firmware operation - nls_933w.dll doesn't match.  

Here's the hashes we have in the output, but, don't see these hashes in your IOCs files.

 MD5: 83b94b1ca8ec061e8fd0364d128d2b2e SHA1: de462481d6fd50d33b22bcf52918a75b69aa41ab SHA256: e727b7dd55428bc1782fc5dd9a977b6a0087ba53b716359e2902f881d4a6ef41 MATCHES: Str1: nls_933w.dll

**Comment by Neo23x0** [comment]
Hi gretty, 

the hashes are the generated hashes for the detected sample. 
It's actually a YARA rule match that triggers the alert message. The rule looks for "nls_933w.dll" in the file content. 
If the file is an executable, I'd recommend a deeper analysis. 
I cannot find the hashes somewhere online, which is suspicious in case that the files are executables and found in typical system locations. 

- Florian
