### ISSUE TITLE
UnboundLocalError: local variable 'ioc_filename' referenced before assignment

### ISSUE THREAD

**Issue by iliaselmatani** [Neo23x0/Loki#52]
Loki failes to run:

:~/tools/Loki$ python loki.py 
                                                                               
  
                             
                             
                             
  
  Simple IOC Scanner
  
  (C) Florian Roth
  August 2016
  Version 0.15.6
  
  DISCLAIMER - USE AT YOUR OWN RISK
  
                                                                               

[NOTICE] Starting Loki Scan SYSTEM: host TIME: 20160902T12:00:09Z PLATFORM: linux   
Traceback (most recent call last):
  File "loki.py", line 811, in initialize_filename_iocs
    for ioc_filename in os.listdir(ioc_directory):
OSError: [Errno 2] No such file or directory: '/home/ilias/tools/Loki/./signature-base/iocs/'
Traceback (most recent call last):
  File "loki.py", line 1257, in <module>
    loki = Loki(args.intense)
  File "loki.py", line 119, in __init__
    self.initialize_filename_iocs(self.ioc_path)
  File "loki.py", line 863, in initialize_filename_iocs
    logger.log("ERROR", "Error reading File IOC file: %s" % ioc_filename)
UnboundLocalError: local variable 'ioc_filename' referenced before assignment

**Comment by Neo23x0** [comment]
See https://github.com/Neo23x0/Loki/issues/51
