### ISSUE TITLE
Exclude options?

### ISSUE THREAD

**Issue by juju4** [Neo23x0/Loki#54]
Hello

you list in releases recommendations to not scan some dir
https://github.com/Neo23x0/Loki/releases
but it does not seem there is any exclude pattern option either from cli, either from file.

would be a nice addition

Thanks

**Comment by Neo23x0** [comment]
Feature added in v0.16.2
https://github.com/Neo23x0/Loki/blob/master/README.md#user-defined-scan-excludes

**Comment by juju4** [comment]
That was fast :-) Thanks @Neo23x0 !
