### ISSUE TITLE
IOC_Filename + Yara_rules issue

### ISSUE THREAD

**Issue by Jefferyah** [Neo23x0/Loki#57]
Hi, Florian!

I tested 0.18.2 version again...
Now 0.18.2 can detect IOC_Filename+yara rules, scores have addition.

BUT
1.Yara rules hit item not display.
2.IOC_Filename hit item repeat display.

Thank you

**Comment by Neo23x0** [comment]
To 1) Please use the "--allreasons" parameter to display all scoring reasons
To 2) Only possible if multiple regular expressions match on the file name

**Comment by Jefferyah** [comment]
OK, I think I get it. ^^

**Comment by Jefferyah** [comment]
I tested 0.18.1-2 on some computers will have this problem...
![2016-12-24_172522](https://cloud.githubusercontent.com/assets/24707050/21466348/f996e444-ca02-11e6-900b-29943e4b1cbc.png)

ps. "存取被拒" = Permission denied
