### ISSUE TITLE
Invoke_mimikatz alert

### ISSUE THREAD

**Issue by antonioCoco** [Neo23x0/Loki#58]
I ran my scan with Loki and i received on all my clients (10 in total) the following alert:

20161229T09:59:24Z PC_NAME LOKI: Alert: Yara Rule MATCH: Invoke_Mimikatz PID: 1524 NAME: SearchProtocolHost.exe CMD: "C:\windows\system32\SearchProtocolHost.exe" Global\UsGthrFltPipeMssGthrPipe7_ Global\UsGthrCtrlFltPipeMssGthrPipe7 1 -2147483646 "Software\Microsoft\Windows Search" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT; MS Search 4.0 Robot)" "C:\ProgramData\Microsoft\Search\Data\Temp\usgthrsvc" "DownLevelDaemon" 

Is it a false positive or should i investigate more on that alert?
Thank you for your support 

Antonio

**Comment by Neo23x0** [comment]
The rule that triggered was the following one

```
rule Invoke_Mimikatz {
	meta:
		description = "Detects Invoke-Mimikatz String"
		author = "Florian Roth"
		reference = "https://github.com/clymb3r/PowerShell/tree/master/Invoke-Mimikatz"
		date = "2016-08-03"
	strings:
		$x1 = "Invoke-Mimikatz" wide fullword
	condition:
      1 of them
}
```

I suppose that the "SearchProtocolHost.exe" process started indexing the LOKI signature files on disk and that's why the "Invoke-Mimikatz" keyword made its way into memory of that process.

**Comment by antonioCoco** [comment]
Is there a way to fix that behaviour or maybe should I tune some false positive Yara rule? thank you for your support

**Comment by Neo23x0** [comment]
Sorry for the late reply. I would simply filter out this specific alert where you analyze the results.

**Comment by azfayel** [comment]
How to ensure that are false positives ? Code improvement ?

**Comment by Neo23x0** [comment]
If it's `SearchProtocolHost.exe` and the `Invoke_Mimikatz` YARA rule matching on that process memory than it is most likely a false positive. I could change the code and exclude some rules from process memory matching. Low prio task.

**Comment by lctrcl** [comment]
I can confirm that this was triggered also while doing the scan. IMHO, would be useful to have this at least in the documentation somewhere as "Possible FPs".

**Comment by Neo23x0** [comment]
I'll apply it to files only by setting a "filesize" in the condition of this rule. This should help.
