### ISSUE TITLE
Cannot update [from binary]

### ISSUE THREAD

**Issue by Epicism** [Neo23x0/Loki#60]
Hello,

When I execute the command "loki.exe --update --debug" I get the following output:
    _    ___  _  _____
   | |  / _ \| |/ /_ _|
   | |_| (_) | ' < | |
   |____\___/|_|\_\___|
    ___ ___   ___   ___
   |_ _/ _ \ / __| / __| __ __ _ _ _  _ _  ___ _ _
    | | (_) | (__  \__ \/ _/ _` | ' \| ' \/ -_) '_|
   |___\___/ \___| |___/\__\__,_|_||_|_||_\___|_|

   (C) Florian Roth
   November 2016
   Version 0.17.1

   DISCLAIMER - USE AT YOUR OWN RISK

Traceback (most recent call last):
  File "<string>", line 1296, in update_signatures
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\git.cmd", line 466, in <lambda>
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\git.cmd", line 910, in _call_process
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\git.cmd", line 630, in execute
GitCommandNotFound: [Error 2] The system cannot find the file specified
[ERROR] Update failed - run with (--debug) to see details

I'm using the https://github.com/Neo23x0/Loki/releases/download/v0.18.2/loki_0.18.2.zip binary.

Thank you for your help.

**Comment by Neo23x0** [comment]
I cannot reproduce this error. Could you tell me more about the environment?

Windows Version?
How and where do you execute the "loki.exe"? (From which path, while you are in the folder or from somewhere else?)
Have you tried it on another system?

**Comment by Epicism** [comment]
Hi Neo23x0,

To answer your questions:
 1. Windows version 10
 2. from cmd.exe in the directory the exe is located (C:\Users\<username>\Downloads\loki_0.18.2\loki)
 3. I tried running it from another VM and I get the same error

Do you have an X: drive? Try renaming X:\pyInstaller-2.1 and seeing if you still don't get the issue.

**Comment by Neo23x0** [comment]
No, drive X: is not needed. That's a path on the build system. 
Program runs fine on Win10 x64 machine without a drive X. 

Could you check if you have Unicode characters in you program path?

**Comment by Epicism** [comment]
No, the full path is C:\Users\epicism\Downloads\loki_0.18.2\loki\loki.exe

Did you try with the binary from the ZIP that I pasted above or a different binary?

**Comment by gregkcarson** [comment]
Hi I have the same issue when running loki.exe --update --debug

**Comment by Gamarala** [comment]
I can confirm I have the same issue running loki_0.18.2 on Win 10 64-bit

**Comment by Neo23x0** [comment]
Could you check if Windows Defender is the reason for this by deactivating it?
My Win10 VMs have forcibly deactivated Windows Defender for testing purposes.

**Comment by Neo23x0** [comment]
Ok, I can reproduce the error on a Windows 2012 Server system. 
I'll check what's the issue and provide a fixed version.

**Comment by Neo23x0** [comment]
Version 0.19.0 should fix this problem

**Comment by Epicism** [comment]
Thank you for your help on this.
