### ISSUE TITLE
Understanding get-OTX output

### ISSUE THREAD

**Issue by jcail** [Neo23x0/Loki#61]
Just double checking to make sure I've got my OTX connector right, and understanding the output from the get-otx-iocs.exe.  Several (quick/easy) questions, and the output of get-otx-iocs.exe -k [API KEY] is below.  

I get several File "X", line X, in...  does this mean that the rule is an overlap elsewhere?  
What is the AttributeError at the end?
Is the return code of -1 a successful execution?

Starting OTX feed download ...
Traceback (most recent call last):
  File "<string>", line 148, in <module>
  File "<string>", line 53, in get_iocs_last
  File "site-packages\OTXv2.py", line 67, in getall
  File "site-packages\OTXv2.py", line 54, in get
AttributeError: 'URLError' object has no attribute 'code'
get-otx-iocs returned -1

Lastly, when I run Loki, I only see the yara rules initialize at the beginning.  Is there a way to validate in the logs that it is checking the otx rules as well (--allreasons)??

Thanks!

**Comment by Neo23x0** [comment]
Maybe the OTX receiver is outdated. It seems that it expects a "code" attribute that isn't there anymore.

**Comment by jcail** [comment]
Ok - when I run that script (get-otx-iocs.exe), it does appear to populate the related files (otx-c2-iocs, otx-filename-iocs, and ots-hash-iocs).  Is there a way for me to validate that these are being checked?  I only see it initializing the yara rules when executing.

**Comment by Neo23x0** [comment]
It is right on top - but hidden in the total amount of IOCs per type

```

[NOTICE] Starting Loki Scan SYSTEM: PROMETHEUS TIME: 20170201T10:19:31Z PLATFORM: windows
[INFO] File Name Characteristics initialized with 1705 regex patterns
[INFO] C2 server indicators initialized with 27358 elements
[INFO] Malicious MD5 Hashes initialized with 13481 hashes
[INFO] Malicious SHA1 Hashes initialized with 5175 hashes
[INFO] Malicious SHA256 Hashes initialized with 14870 hashes
[INFO] False Positive Hashes initialized with 30 hashes
```

You could remove/add the otx-* files and check if the numbers change. I'll add that to the debugging output if it is not already included.

**Comment by jcail** [comment]
That works for me - thanks!
