### ISSUE TITLE
Errors when installing yara rules

### ISSUE THREAD

**Issue by zappeee** [Neo23x0/Loki#64]
I get this error when installing

[INFO] Initializing Yara rule apt_sphinx_moth.yar
Traceback (most recent call last):
  File "<string>", line 971, in initialize_yara_rules
SyntaxError: C:\Users\XXX\Downloads\loki_0.19.1\loki\./signature-base/yara\apt_stonedrill.yar(31): invalid field name "number_of_signatures"

**Comment by Neo23x0** [comment]
Ah - thanks. That's most likely due to the missing OpenSSL in the compiled Python libraries. I'll check if I can modify the rule.

**Comment by Neo23x0** [comment]
Fixed
