### ISSUE TITLE
Make it run under Cygwin

### ISSUE THREAD

**Issue by topiux** [Neo23x0/Loki#66]
Having the option to use a bash shell for the convenience of execution and output manipulation would be beneficial. Currently, execution of the windows binary in Cygwin ends up in error:

```
$ ./loki.exe


      __    ____  __ __ ____
     / /   / __ \/ //_//  _/
    / /   / / / / ,<   / /
   / /___/ /_/ / /| |_/ /
  /_____/\____/_/ |_/___/
      ________  ______   _____
     /  _/ __ \/ ____/  / ___/_________ _____  ____  ___  _____
     / // / / / /       \__ \/ ___/ __ `/ __ \/ __ \/ _ \/ ___/
   _/ // /_/ / /___    ___/ / /__/ /_/ / / / / / / /  __/ /
  /___/\____/\____/   /____/\___/\__,_/_/ /_/_/ /_/\___/_/


   (C) Florian Roth
   February 2017
   Version 0.19.1

   DISCLAIMER - USE AT YOUR OWN RISK



Traceback (most recent call last):
  File "<string>", line 1467, in <module>
  File "<string>", line 1197, in log
  File "<string>", line 1208, in log_to_stdout
TypeError: encode() argument 1 must be string, not None
```

**Comment by Neo23x0** [comment]
Can't you just install python and yara-python module in cygwin and run the python script?

**Comment by topiux** [comment]
That's what I ended up doing. Few more steps but worth it. The CMD window is too restrictive.

**Comment by Winterspite** [comment]
So I'm looking to make this a deployable tool in an IR framework I've cobbled together and would like to be able to throw this onto a random client machine. When I'm running loki via wmiexec.py on a remote Windows machine, I get this exact same error. If I run Loki on the remote machine by hand, it works fine.

As I'd prefer not to have to install cygwin/python/yara-python on all remote systems, I'd prefer to stick with the executable - but am not sure why it's failing.

**Comment by Neo23x0** [comment]
Could you do the following on the machine your are running the wmiexec

Start python console
```python```

Then
```
import sys
print sys.stdout.encoding
```
-- 
Sincerely
Saludos cordiales
Mit freundlichen Grüßen
Florian Roth

Key material (S/MIME, PGP, Threema):
https://www.dropbox.com/sh/lw9ymama8rjukjs/zNQZAujnQM

**Comment by GREEKYnikhilsharma** [comment]
yes it is
