### ISSUE TITLE
Decoding error while checking Double Pulsar

### ISSUE THREAD

**Issue by halos** [Neo23x0/Loki#68]
Version: 0.20.0
In a spanish computer, after updating the database, I execute `loki.exe` without parameters as administrador and while checking Double Pulsar, Loki completely crashes. This is all the information shown in the terminal:
```
[INFO] Checking for Double Pulsar RDP Backdoor
Traceback (most recent call last):
  File "<string>", line 1530, in <module>
  File "<string>", line 841, in check_rootkit
  File "<string>", line 1229, in log
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 85: ordinal not in range(128)
```

The log file doesn't contain more information.

**Comment by Neo23x0** [comment]
Please check version 0.20.1

https://github.com/Neo23x0/Loki/releases/tag/0.20.1

**Comment by halos** [comment]
Executed the version 0.20.1 in the same machine several times and Loki worked perfectly.
