### ISSUE TITLE
Loki- Double Pulsar RDP Check

### ISSUE THREAD

**Issue by CyberSuck** [Neo23x0/Loki#69]
upon running Loki in windows VM  i get the below error in regards to double pulsar -- appreciate your help here. Thank you. by the way, its a cool program :) Thank you.
 Checking for Backdoors ...
 Checking for Double Pulsar RDP Backdoor
 **Double Pulsar RDP check failed RESULT: Connection failure**
 Checking for Double Pulsar SMB Backdoor
 Double Pulsar SMB check failed RESULT: Connection failure
 Scanning C:\Progs\badstuff ...
E] Results: 0 alerts, 0 warnings, 26 notices

**Comment by Neo23x0** [comment]
It cannot connect to an open RDP port. That may be normal if RDP isn't running.
