### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by moyatvoya** [Neo23x0/Loki#70]
Hi! I downloaded loki 0.20.1 the first time and run it:

Traceback (most recent call last):
  File "<string>", line 1496, in <module>
  File "<string>", line 1229, in log
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 27: ordinal
 not in range(128)

how do I run loki?

**Comment by Neo23x0** [comment]
Do not run it from a directory that contains unicode characters

**Comment by moyatvoya** [comment]
I do not know what I did, but it started
Thanks
