### ISSUE TITLE
ascii' codec can't decode byte 0xbf in position 23

### ISSUE THREAD

**Issue by takenek** [Neo23x0/Loki#73]
Hey i got strange problem with Loki:

[INFO] Scanning C:\ ...                                                                                                 [
[WARNING]
FILE: C:\Program Files (x86)\Kaspersky Lab\Kaspersky Anti-Virus 17.0.0\avzkrnl.dll SCORE: 70 TYPE: EXE SIZE: 2155944
FIRST_BYTES: 4d5a50000200000004000f00ffff0000b8000000 / MZP
MD5: 41f44b8f26099e38c8107ac5af090b59
SHA1: 384573a54e6479390e61f0be00dae0968b749301
SHA256: 11da3408294521bf53d7d5dd14a58ec4fa7b8d90c523558cc815050526ca475d CREATED: Tue Jun 28 00:17:46 2016 MODIFIED: Tu
 Jun 28 00:17:46 2016 ACCESSED: Sun May 28 12:19:58 2017
REASON_1: Yara Rule MATCH: CookieTools SUBSCORE: 70
DESCRIPTION: Chinese Hacktool Set - file CookieTools.exe
MATCHES: Str1: No data to read.$Can not bind in port range (%d - %d) Str2: Connection Closed Gracefully.;Could not bind
socket. Address and port are ... (truncated)
Traceback (most recent call last):
  File "<string>", line 1334, in <module>
  File "<string>", line 171, in scan_path
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 281, in walk
  File "<string>", line 1225, in walk_error
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 64, in log
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 23: ordinal not in range(128)

Version 0.21 for windows and Signature from here: https://github.com/Neo23x0/signature-base/archive/master.zip

Best Regards

**Comment by Neo23x0** [comment]
Can you run the following command for me:

```loki.exe --noprocs --printAll -p "C:\Program Files (x86)\Kaspersky Lab\Kaspersky Anti-Virus 17.0.0"```

I'd like to see which file causes the Unicode error.

**Comment by takenek** [comment]
This is log: https://taken.pl/loki.log

Best Regards

**Comment by Neo23x0** [comment]
Ah - damn. The ascii codec error isn't caused by a file in the Kaspersky folder but somewhere else in the walk. I'll try to handle that in the code and produce a bugfix.

**Comment by Neo23x0** [comment]
Please check the bugfix version 0.21.1 here:
[https://keybase.pub/johngalt/Share/](https://keybase.pub/johngalt/Share/)

It should print an error, remove all non-ascii characters from the STDOUT message but print the full UNICODE message to the log file.

**Comment by takenek** [comment]
Are you sure there will be log? I don`t get it on screen got it this:
NFO] Double Pulsar SMB check failed RESULT: Connection failure                                                        [I
NFO] Scanning C:\ ...                                                                                                  \
Cannot print certain characters to command line - see log file for full unicode encoded log line                      [E
RROR] [Error 3] System nie moe odnale okrelonej cieki: u'C:\\Program Files (x86)\\NVIDIA Corporation\\NvContainer\\plugi
ns\\LocalSystem\\NvBackend\\*.*'
Traceback (most recent call last):
  File "<string>", line 1334, in <module>
  File "<string>", line 171, in scan_path
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 281, in walk
  File "<string>", line 1225, in walk_error
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 73, in log
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 152, in log_to_file
NameError: global name 'traceback' is not defined
PS D:\a>

**Comment by Neo23x0** [comment]
Ah - no - another error. (will fix that too)
But we can see what's going wrong:

```[E
RROR] [Error 3] System nie moe odnale okrelonej cieki: u'C:\Program Files (x86)\NVIDIA Corporation\NvContainer\plugi
ns\LocalSystem\NvBackend\.'```

This error message he'd like to print has some line breaks in it that seem to be interpreted. I have to check how this error message is generated and why it isn't interpreted as raw string.

**Comment by Neo23x0** [comment]
Ah - it's a walk error:

[https://github.com/Neo23x0/Loki/blob/master/loki.py#L1223](https://github.com/Neo23x0/Loki/blob/master/loki.py#L1223)

```
def walk_error(err):
    if "Error 3" in str(err):
        logger.log("ERROR", str(err))
    if args.debug:
        traceback.print_exc()
```

The walk error message generated by your OS includes unicode characters.
Next month I have holidays - maybe I'll port everything to Python 3 to get rid of that unicode sh** in Python 2.
Will think about a workaround.

**Comment by takenek** [comment]
"System nie moe odnale okrelonej cieki" - he "skip polish letter proper is:
"System nie może odnaleźć określonej ścieżki" - possible there is a problem :-)

**Comment by Neo23x0** [comment]
Could you please check this version
[https://keybase.pub/johngalt/Share/loki_0.21.1b.zip](https://keybase.pub/johngalt/Share/loki_0.21.1b.zip)

```loki.exe --noprocs -p "C:\Program Files (x86)\NVIDIA Corporation\NvContainer\plugi
ns\LocalSystem"```

**Comment by takenek** [comment]
20170617T10:26:52Z SERWER LOKI: Info: Initialized all Yara rules at once
20170617T10:26:52Z SERWER LOKI: Info: Current user has admin rights - very good
20170617T10:26:52Z SERWER LOKI: Info: Setting LOKI process with PID: 4632 to priority IDLE
20170617T10:26:52Z SERWER LOKI: Info: Checking for Backdoors ...
20170617T10:26:52Z SERWER LOKI: Info: Checking for Double Pulsar RDP Backdoor
20170617T10:26:52Z SERWER LOKI: Info: Double Pulsar RDP check RESULT: Server requires NLA, which DOUBLEPULSAR does not support
20170617T10:26:52Z SERWER LOKI: Info: Checking for Double Pulsar SMB Backdoor
20170617T10:26:52Z SERWER LOKI: Info: Double Pulsar SMB check failed RESULT: Connection failure
20170617T10:26:52Z SERWER LOKI: Info: Scanning C:\Program Files (x86)\NVIDIA Corporation\NvContainer\plugins\LocalSystem ...  
20170617T10:26:52Z SERWER LOKI: Error: 
20170617T10:26:52Z SERWER LOKI: Notice: Results: 0 alerts, 0 warnings, 2 notices
20170617T10:26:52Z SERWER LOKI: Result: SYSTEM SEEMS TO BE CLEAN.
20170617T10:26:52Z SERWER LOKI: Notice: Finished LOKI Scan SYSTEM: SERWER TIME: 20170617T10:26:52Z

**Comment by Neo23x0** [comment]
Thanks a lot. I'll try to raise my own errors with unicode characters and debug the issue until a bugfix is ready. Thanks for your help!

**Comment by takenek** [comment]
You welcome, if You need any more try write here i will be whole saturday and sunday near computer.

**Comment by Neo23x0** [comment]
Ah - nice. 
Please check [https://keybase.pub/johngalt/Share/](https://keybase.pub/johngalt/Share/) for 0.21.1c and try this version.

**Comment by takenek** [comment]
NFO] Scanning C:\ ...                                                                                                  \
Traceback (most recent call last):
  File "<string>", line 1338, in <module>
  File "<string>", line 171, in scan_path
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 281, in walk
  File "<string>", line 1228, in walk_error
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 21: ordinal not in range(128)
PS D:\Loki>

**Comment by Neo23x0** [comment]
WTF ... :D 
Did you run it with the "--debug" switch? If yes, try it without the "--debug" switch.

**Comment by takenek** [comment]
i run without debug just loki.exe nothing else.

**Comment by takenek** [comment]
This is with debug option:

Sending tree connect
[INFO] Double Pulsar SMB check failed RESULT: Connection failure
Traceback (most recent call last):
  File "<string>", line 841, in check_rootkit
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.doublepulsar", line 108, in check_ip_smb
error: [Errno 10054] Istniej╣ce po│╣czenie zosta│o gwa│townie zamkniŕte przez zdalnego hosta
[INFO] Scanning C:\ ...
[DEBUG] Cannot open file C:\pagefile.sys (access denied)
Traceback (most recent call last):
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.helpers", line 204, in get_file_type
IOError: [Errno 13] Permission denied: u'C:\\pagefile.sys'
[DEBUG] Cannot open file C:\swapfile.sys (access denied)
Traceback (most recent call last):
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.helpers", line 204, in get_file_type
IOError: [Errno 13] Permission denied: u'C:\\swapfile.sys'
\Traceback (most recent call last):
  File "<string>", line 1338, in <module>
  File "<string>", line 171, in scan_path
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 296, in walk
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\os", line 281, in walk
  File "<string>", line 1228, in walk_error
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 21: ordinal not in range(128)

D:\Loki>

**Comment by Neo23x0** [comment]
It's hard to debug this, as I cannot reproduce the error here on my system. 

[https://keybase.pub/johngalt/Share/loki_0.21.1d.zip](https://keybase.pub/johngalt/Share/loki_0.21.1d.zip)

**Comment by takenek** [comment]
Looks like working this time:

NFO] Scanning memory dump file C:\Users\All Users\Origin\Logs\R.10,3,3,1921 SERWER 16-12-16 17.33.45.mdmp             [I
NFO] Scanning memory dump file C:\Users\All Users\Origin\Logs\R.10,4,2,12697 SERWER 17-02-03 16.25.41.mdmp            [N
OTICE]
FILE: C:\Users\All Users\Razer\Synapse\ProductUpdates\Uninstallers\RazerFonts\RazerFonts_Uninstaller.exe SCORE: 45 TYPE:
 EXE SIZE: 32206
FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
MD5: ff49b47515bba03510be96f8b6b11d0f
SHA1: ac11068643694673febd809fa1a9bf3ba22caf9e
SHA256: 85337c01ccf96de375f2d77a2db95bb24bc013f9d2dfdafdcdb21c335ac6a620 CREATED: Sun Aug 16 08:43:46 2015 MODIFIED: Sun
 Aug 16 08:43:46 2015 ACCESSED: Sun Aug 16 08:43:46 2015
REASON_1: File Name IOC matched PATTERN: Fonts\\[\w]+\.exe$ SUBSCORE: 45 DESC: ThreatExpert Statistics                [N
OTICE] Results: 0 alerts, 38 warnings, 76 notices                                                                     [R
ESULT] Suspicious objects detected!                                                                                   [R
ESULT] Loki recommends a deeper analysis of the suspicious objects.                                                   [N
OTICE] Finished LOKI Scan SYSTEM: SERWER TIME: 20170617T12:23:47Z

Press Enter to exit ...
PS D:\Loki>

You want loki-SERWER.log file to check?

**Comment by Neo23x0** [comment]
Ok, thanks for the help! I published a new release on Saturday.
