### ISSUE TITLE
false positives and/or alert questions

### ISSUE THREAD

**Issue by gunnersson** [Neo23x0/Loki#8]
Dear all,

using LOKI v0.7 I got:

1)
May 14 22:12:54 MR_WHISPER LOKI: File Name IOC matched PATTERN: \\windows\.exe$ DESC: ThreatExpert Statistics MATCH: C:\Program Files (x86)\Malwarebytes Anti-Malware\Chameleon\Windows\windows.exe
May 14 22:12:55 MR_WHISPER LOKI: Yara Rule MATCH: winlogon_ANOMALY FILE: C:\Program Files (x86)\Malwarebytes Anti-Malware\Chameleon\Windows\winlogon.exe MD5: 195ed6a960d79116c9b5d8d541946a21 SHA1: 14f3e6b05e5693b1cbd9091bafe2649f830799a3 SHA256: dd4afc38cd49fd8b25d2babb53b5cceada3052fbb9669e146d1500619f50a2d9 MATCHES: 

(Probably) belongs to 
<https://www.malwarebytes.org/>
<https://www.malwarebytes.org/antimalware/premium/>
<https://www.malwarebytes.org/chameleon/>

2.a)
May 14 23:45:02 MR_WHISPER LOKI: Malware Hash TYPE: SHA1 HASH: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3 FILE: C:\Windows\System32\catroot\{F750E6C3-38EE-11D1-85E5-00C04FC295EE}\oem139.cat DESC: APTnotes 2014 Miniduke_twitter.pdf

VT shows <https://www.virustotal.com/de/file/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08/analysis/>.
Former versions of LOKI haven't reported this one (as far as I remember...)

2.b)
May 14 23:56:41 MR_WHISPER LOKI: Malware Hash TYPE: SHA1 HASH: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3 FILE: C:\Windows\System32\DriverStore\FileRepository\nf4sys.inf_amd64_neutral_8582e32df21c4bc2\nf4sys.cat DESC: APTnotes 2014 Miniduke_twitter.pdf

VT shows <https://www.virustotal.com/de/file/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08/analysis/>.
Former versions of LOKI haven't reported this one (as far as I remember...)

2.c)
2.a) and 2.b) throw the same SHA256 but are named differently.

3.)
May 14 21:34:45 MR_WHISPER LOKI: Error while process memory Yara check (maybe the process doesn't exist anymore or access denied). PID: 1056 NAME: audiodg.exe

What does this mean?

Thank you.

Gunner

**Comment by Neo23x0** [comment]
I integrated the Hash IOC list from APTNotes. 
http://aptnotes.malwareconfig.com/

I expected it to contain some false positives.

The process check error is thrown when a process that was in the list at the beginning of the check  disappeared when the loop starts checking the respective process. Normally, this is a sign of a process that was terminated before it could be checked. If you want more info, try using the "--debug" switch.

**Comment by gunnersson** [comment]
FP detection (newly/again?):

[ALERT] File Name IOC matched PATTERN: [^\s]\\windows\.exe$ DESC: ThreatExpert Statistics MATCH: C:\Program Files (x86)\Malwarebytes Anti-Malware\Chameleon\Windows\windows.exe

Please, refer to
https://www.malwarebytes.org/
https://www.malwarebytes.org/chameleon/

Thank you,

Gunner

**Comment by gunnersson** [comment]
[ALERT] File Name IOC matched PATTERN: [^\s]\\windows\.exe$ DESC: ThreatExpert Statistics MATCH: C:\Program Files (x86)\Malwarebytes Anti-Malware\Chameleon\Windows\windows.exe

https://www.malwarebytes.org/
https://www.malwarebytes.org/antimalware/
https://www.malwarebytes.org/antimalware/premium/
https://www.malwarebytes.org/chameleon/

**Comment by Neo23x0** [comment]
Removed
