### ISSUE TITLE
with loki_0.24.0 I have many record at the log file:  yara(24 or 25): invalid field name "md5"

### ISSUE THREAD

**Issue by vsh77** [Neo23x0/Loki#80]
Hello

with loki_0.24.0 I have many record at the log file:  yara(24 or 25): invalid field name "md5"

yara(25): invalid field name "md5"
yara(24): invalid field name "md5"

![image](https://user-images.githubusercontent.com/26473947/30249721-8976ab80-964a-11e7-92c7-f80af47a7a79.png)

**Comment by jonaslejon** [comment]
This is probably due to that **yara** has been compiled without crypto-support or that the crypto-lib does not support **md5**.

**Comment by GREEKYnikhilsharma** [comment]
facing same issue after installing python-yara 3.6.3 (crypto support ? in windows ??)

**Comment by Neo23x0** [comment]
Issue is YARA related - see issue and my comment :
https://github.com/Neo23x0/Loki/issues/79
