### ISSUE TITLE
false IOC 

### ISSUE THREAD

**Issue by azfayel** [Neo23x0/Loki#86]
Hello,

I submit a potentially false positive in IOC, maybe need some tuning.
[ALERT]
FILE: C:\Program Files (x86)\McAfee\VirusScan Enterprise\ScnCfg32.Exe SCORE: 100 TYPE: EXE SIZE: 48488
FIRST_BYTES: 4d5a90000300000004000000ffff0000b8000000 / MZ
MD5: b5bdaba69689e8be57ce78bb6845e4f0
SHA1: 573c35ab1f243d6806dedbdd7e3265bc5cbd5b9a
SHA256: 1e712adae2a543bf2fbf41691416b350c3a90561ab5f6590e520f833a9a587ad
CREATED: Wed Jan 15 20:08:00 2014 MODIFIED: Wed Jan 15 20:08:00 2014 ACCESSED: Mon Jun 08 15:02:33 2015
REASON_1: Malware Hash TYPE: MD5 HASH: b5bdaba69689e8be57ce78bb6845e4f0 SUBSCORE: 100 DESC: Operation Cloud Hopper (hashes) https://www.pwc.co.uk/issues/cyber-security-data-privacy
/insights/operation-clou

Mcafee vendor says this binary is clean.

**Comment by vwhissell** [comment]
Does indeed seem to be a false positive:
https://www.metadefender.com/#!/results/file/ZTE3MDUwN3JrVlpEOTJnM0otcnktZzk1ZzlTcGI/regular/analysis

**Comment by vwhissell** [comment]
But, I think you should report there:
https://github.com/Neo23x0/signature-base

This where the IOCs are "stored"

**Comment by Neo23x0** [comment]
Fixed - some time ago

**Comment by Neo23x0** [comment]
I notified the author

https://otx.alienvault.com/pulse/58e2ab24ddde682bea60ef18/comments
