### ISSUE TITLE
Encode() Argument must not be none

### ISSUE THREAD

**Issue by vwhissell** [Neo23x0/Loki#87]
Hello,
The use case is this:

1) I SSH into a Windows Box using freesshd
I 2) run "_net use v: \\\\COMPUTER\SHARE_"
3) go into v:\
--) the \\COMPUTER\SHARE folder has the release files (loki.exe, loki-upgrader,exe, FOLDER:sugnature-base, and the other files for windows)
4) I run "_loki.exe --nolog -r {SYSLOG_SERVER_IP} --noindicator_"
5) Then, I got this message:

"
```
[...] **LOKI LOGO** [...]
DISCLAIMER - USE AT YOUR OWN RISK
   Please report false positives via https://github.com/Neo23x0/Loki/issues

                                                                           

Cannot print certain characters to command line - see log file for full unicode encoded log line
Traceback (most recent call last):
  File "<string>", line 1405, in <module>
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 90, in log
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 100, in log_to_stdout
TypeError: encode() argument 1 must be string, not None
```
"

To "Bypass that issue, I added the flag "_--onlyrelevant_", but I fear that when it will print something, it will crash.

**Comment by vwhissell** [comment]
Oh, after few minutes (The scan is still running) I go this:

```
Cannot print certain characters to command line - see log file for full unicode encoded log line
Cannot print certain characters to command line - see log file for full unicode encoded log line
Cannot print certain characters to command line - see log file for full unicode encoded log line
Cannot print certain characters to command line - see log file for full unicode encoded log line
```
Also, note that nothing was sent to my syslog server

**Comment by vwhissell** [comment]
What would happen if you change:


File:  Loki/lib/lokilogger.py


`**90**      message = message.encode(sys.stdout.encoding, errors='replace')`
To
`**90**      message = message.encode('**ascii**', errors='replace')`

**Comment by GREEKYnikhilsharma** [comment]
i too did some changes to make it run perfectly in windows

**Comment by Neo23x0** [comment]
Fixed in https://github.com/Neo23x0/Loki/releases/tag/v0.24.3
