### ISSUE TITLE
Is this project actve?

### ISSUE THREAD

**Issue by vwhissell** [Neo23x0/Loki#89]
Also, could you add a flag to select the port to syslog to? By default, it uses port 514.
In  Loki/lib/lokilogger.py: line 56
`remote_syslog_handler = logging.handlers.SysLogHandler(address=(remote_host, 514), facility=19)`
to
remote_syslog_handler = logging.handlers.SysLogHandler(address=(remote_host, self.remote_port), facility=19)

Add
remote_port in:
```
def __init__([...],remote_port)
self.remote_port = remote_port
```
Change line 1396 of  Loki/loki.py by adding the remote_port:
```
logger = LokiLogger(args.nolog, args.l, t_hostname, args.r, args.csv, args.onlyrelevant, args.debug,
platform=platform, caller='main',args.remote_port)
```

Might have some other stuff to do... I'm not a Python dev. I'm only a simple Security Analyst :(

**Comment by GREEKYnikhilsharma** [comment]
=D

**Comment by Neo23x0** [comment]
Yes, it's active. I just noticed that I didn't receive notifications for my github projects for the last 3 months or longer. I configured a different notification target.

**Comment by Neo23x0** [comment]
I've implemented the syslog port selection feature (`-r syslogsystem -t port`) in the current master. I have not drafted a new release yet.
