### ISSUE TITLE
False positive: notepad (d378bffb70923139d6a4f546864aa61c)

### ISSUE THREAD

**Issue by hasherezade** [Neo23x0/Loki#94]
A legitimate Notepad from Windows 7 32bit was detected as a malware:
![notepad_false](https://user-images.githubusercontent.com/3115348/34503633-cc20bbd2-f019-11e7-97fd-c022ed5510f1.png)
If you take a closer look at the referenced article: https://blog.cylance.com/operation-cleaver-the-notepad-files - you will notice, that this hash was actually NOT mentioned as a hash of the trojanized notepad, but of a legitimate version, referenced in green:
![notepad_ioc](https://user-images.githubusercontent.com/3115348/34503720-5504aed6-f01a-11e7-8ffc-b7b56b89bf22.png)

**Comment by Neo23x0** [comment]
Fixed in https://github.com/Neo23x0/signature-base/commit/e486ade31ab6d24a0e1da9240c531bd8f39ee45c

This hash has been in an AlienVault OTX feed export.

Thanks
