### ISSUE TITLE
false positive: msvcr71.dll 

### ISSUE THREAD

**Issue by elvisghost** [Neo23x0/Loki#96]
IMHO, false positive.  Because it's ordinary  MS Visual C++ DLL

**LOKI (v.0.25.0 with signature base updated 10 Jan 2018 19:03 GMT) says:**
> REASON_1: Malware Hash TYPE: SHA256 HASH: 8094af5ee310714caebccaeee7769ffb080485
> 03ba478b879edfef5f1a24fefe SUBSCORE: 100 DESC: Crimeware-as-a-Service 
> https://www.virustotal.com/en/ip-address/188.128.173.225/information/ / https://

**Virustotal says:
[link](https://www.virustotal.com/en/file/8094af5ee310714caebccaeee7769ffb08048503ba478b879edfef5f1a24fefe/analysis/1515586698/)**
> SHA256: | 8094af5ee310714caebccaeee7769ffb08048503ba478b879edfef5f1a24fefe
> File name: | 8094af5ee310714c_msvcr71.dll
> Detection ratio: | 0 / 67
> Analysis date: | 2018-01-10 12:18:18 UTC              ( 7 hours, 26 minutes ago )

**Comment by Neo23x0** [comment]
It was a nother hash false positive from an AlienVault OTX pulse. I removed the hash, put it in a whitelist and reported the hash to the pulse owner so that he can remove it. 
https://otx.alienvault.com/pulse/57e928543f5d465dafc74a78
