### ISSUE TITLE
svchost owner

### ISSUE THREAD

**Issue by DimChris0** [Neo23x0/Loki#97]
Hello,

when scanning the memory and the svchost.exe process is found and checked, I get a warning when I am 
the owner. Is this normal? Should I add an exclusion when it sees also me or is it dangerous? If I could 
avoid seeing this warning any tips would be welcome

**Comment by robsmallridge** [comment]
svchost is the process space for processes which are running as a service, this typically includes exe/dlls which are loaded into the svchost process space.  IIRC: Typically the svchost process will run under a few select usernames, some are: 

SYSTEM
Network Service
Local Service
etc.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms686005%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

Sometimes Malware authors use legitimate process names to go hidden in plain site.
 
If you have a svchost.exe process running under your own user, this could be a malicious process and probably warrants further investigation. I would check first to see whether that is a legitimate svchost.exe process image (check the path, hash and signature). If it is, I would then inspect what dlls are loaded into this address space.  

Hope this helps
